/* guokr */G.def("ga",function(){window._bdhmProtocol="https:"==document.location.protocol?"https://":"http://";window._gaq=window._gaq||[];_gaq.push(["_setAccount","UA-19521615-1"]);_gaq.push(["_trackPageview"]);_gaq.push(["_trackPageLoadTime"]);var j=document.getElementsByTagName("script")[0],r=document.createElement("script"),q=document.createElement("script");r.type="text/javascript";r.async=!0;r.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";q.type="text/javascript";
q.async=!0;q.src=_bdhmProtocol+"hm.baidu.com/h.js?95dfd07652f91dffd9647f46a3ca9fab";j.parentNode.insertBefore(r,j);j.parentNode.insertBefore(q,j)});
G.def("jQuery",function(){function j(a,b,d){if(void 0===d&&1===a.nodeType)if(d=a.getAttribute("data-"+b),"string"===typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:!c.isNaN(d)?parseFloat(d):x.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=void 0;return d}function r(){return!1}function q(){return!0}function o(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function p(a){var b,d,e,f,h,m,k,w,g,l,t,i=[];f=[];h=c.data(this,this.nodeType?"events":"__events__");if("function"===
typeof h)h=h.events;if(!(a.liveFired===this||!h||!h.live||a.button&&"click"===a.type)){a.namespace&&(t=RegExp("(^|\\.)"+a.namespace.split(".").join("\\.(?:.*\\.)?")+"(\\.|$)"));a.liveFired=this;var n=h.live.slice(0);for(k=0;k<n.length;k++)h=n[k],h.origType.replace(K,"")===a.type?f.push(h.selector):n.splice(k--,1);f=c(a.target).closest(f,a.currentTarget);for(w=0,g=f.length;w<g;w++){l=f[w];for(k=0;k<n.length;k++)if(h=n[k],l.selector===h.selector&&(!t||t.test(h.namespace))){m=l.elem;e=null;if("mouseenter"===
h.preType||"mouseleave"===h.preType)a.type=h.preType,e=c(a.relatedTarget).closest(h.selector)[0];(!e||e!==m)&&i.push({elem:m,handleObj:h,level:l.level})}}for(w=0,g=i.length;w<g;w++){f=i[w];if(d&&f.level>d)break;a.currentTarget=f.elem;a.data=f.handleObj.data;a.handleObj=f.handleObj;t=f.handleObj.origHandler.apply(f.elem,arguments);if(!1===t||a.isPropagationStopped())if(d=f.level,!1===t&&(b=!1),a.isImmediatePropagationStopped())break}return b}}function s(a,b){return(a&&"*"!==a?a+".":"")+b.replace(oa,
"`").replace(pa,"&")}function u(a,b,d){if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,a)===d});if(b.nodeType)return c.grep(a,function(a){return a===b===d});if("string"===typeof b){var e=c.grep(a,function(a){return 1===a.nodeType});if(qa.test(b))return c.filter(b,e,!d);b=c.filter(b,e)}return c.grep(a,function(a){return 0<=c.inArray(a,b)===d})}function i(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var b=c.data(a[d++]),f=c.data(this,b);if(b=b&&b.events){delete f.handle;
f.events={};for(var h in b)for(var m in b[h])c.event.add(this,h,b[h][m],b[h][m].data)}}})}function n(a,b){b.src?c.ajax({url:b.src,async:!1,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function g(a,b,d){var e="width"===b?a.offsetWidth:a.offsetHeight;if("border"===d)return e;c.each("width"===b?ra:sa,function(){d||(e-=parseFloat(c.css(a,"padding"+this))||0);e="margin"===d?e+(parseFloat(c.css(a,"margin"+this))||0):e-(parseFloat(c.css(a,
"border"+this+"Width"))||0)});return e}function B(a,b,d,e){c.isArray(b)&&b.length?c.each(b,function(b,h){d||ta.test(a)?e(a,h):B(a+"["+("object"===typeof h||c.isArray(h)?b:"")+"]",h,d,e)}):!d&&null!=b&&"object"===typeof b?c.isEmptyObject(b)?e(a,""):c.each(b,function(b,c){B(a+"["+b+"]",c,d,e)}):e(a,b)}function y(a,b){var d={};c.each(T.concat.apply([],T.slice(0,b)),function(){d[this]=a});return d}function t(a){if(!P[a]){var b=c("<"+a+">").appendTo("body"),d=b.css("display");b.remove();if("none"===d||
""===d)d="block";P[a]=d}return P[a]}function C(a){return c.isWindow(a)?a:9===a.nodeType?a.defaultView||a.parentWindow:!1}var l=window.document,c=function(){function a(){if(!b.isReady){try{l.documentElement.doScroll("left")}catch(c){setTimeout(a,1);return}b.ready()}}var b=function(a,c){return new b.fn.init(a,c)},c=window.jQuery,e=window.$,f,h=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,m=/\S/,k=/^\s+/,w=/\s+$/,g=/\W/,t=/\d/,i=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,n=/^[\],:{}\s]*$/,o=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
p=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,r=/(?:^|:|,)(?:\s*\[)+/g,s=/(webkit)[ \/]([\w.]+)/,v=/(opera)(?:.*version)?[ \/]([\w.]+)/,E=/(msie) ([\w.]+)/,ua=/(mozilla)(?:.*? rv:([\w.]+))?/,F=navigator.userAgent,U=!1,H=[],j,q=Object.prototype.toString,u=Object.prototype.hasOwnProperty,C=Array.prototype.push,y=Array.prototype.slice,z=String.prototype.trim,B=Array.prototype.indexOf,x={};b.fn=b.prototype={init:function(a,c){var d,e,v;if(!a)return this;if(a.nodeType)return this.context=
this[0]=a,this.length=1,this;if("body"===a&&!c&&l.body)return this.context=l,this[0]=l.body,this.selector="body",this.length=1,this;if("string"===typeof a){if((d=h.exec(a))&&(d[1]||!c)){if(d[1])return v=c?c.ownerDocument||c:l,(e=i.exec(a))?b.isPlainObject(c)?(a=[l.createElement(e[1])],b.fn.attr.call(a,c,!0)):a=[v.createElement(e[1])]:(e=b.buildFragment([d[1]],[v]),a=(e.cacheable?e.fragment.cloneNode(!0):e.fragment).childNodes),b.merge(this,a);if((e=l.getElementById(d[2]))&&e.parentNode){if(e.id!==
d[2])return f.find(a);this.length=1;this[0]=e}this.context=l;this.selector=a;return this}return!c&&!g.test(a)?(this.selector=a,this.context=l,a=l.getElementsByTagName(a),b.merge(this,a)):!c||c.jquery?(c||f).find(a):b(c).find(a)}if(b.isFunction(a))return f.ready(a);if(void 0!==a.selector)this.selector=a.selector,this.context=a.context;return b.makeArray(a,this)},selector:"",jquery:"1.4.4",length:0,size:function(){return this.length},toArray:function(){return y.call(this,0)},get:function(a){return null==
a?this.toArray():0>a?this.slice(a)[0]:this[a]},pushStack:function(a,c,d){var e=b();b.isArray(a)?C.apply(e,a):b.merge(e,a);e.prevObject=this;e.context=this.context;if("find"===c)e.selector=this.selector+(this.selector?" ":"")+d;else if(c)e.selector=this.selector+"."+c+"("+d+")";return e},each:function(a,c){return b.each(this,a,c)},ready:function(a){b.bindReady();b.isReady?a.call(l,b):H&&H.push(a);return this},eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},
last:function(){return this.eq(-1)},slice:function(){return this.pushStack(y.apply(this,arguments),"slice",y.call(arguments).join(","))},map:function(a){return this.pushStack(b.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.prevObject||b(null)},push:C,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var a,c,d,e,f,v=arguments[0]||{},h=1,k=arguments.length,E=!1;"boolean"===typeof v&&(E=v,v=arguments[1]||{},h=2);"object"!==typeof v&&
!b.isFunction(v)&&(v={});k===h&&(v=this,--h);for(;h<k;h++)if(null!=(a=arguments[h]))for(c in a)d=v[c],e=a[c],v!==e&&(E&&e&&(b.isPlainObject(e)||(f=b.isArray(e)))?(f?(f=!1,d=d&&b.isArray(d)?d:[]):d=d&&b.isPlainObject(d)?d:{},v[c]=b.extend(E,d,e)):void 0!==e&&(v[c]=e));return v};b.extend({noConflict:function(a){window.$=e;if(a)window.jQuery=c;return b},isReady:!1,readyWait:1,ready:function(a){!0===a&&b.readyWait--;if(!b.readyWait||!0!==a&&!b.isReady){if(!l.body)return setTimeout(b.ready,1);b.isReady=
!0;if(!(!0!==a&&0<--b.readyWait)&&H){var c=0,d=H;for(H=null;a=d[c++];)a.call(l,b);b.fn.trigger&&b(l).trigger("ready").unbind("ready")}}},bindReady:function(){if(!U){U=!0;if("complete"===l.readyState)return setTimeout(b.ready,1);if(l.addEventListener)l.addEventListener("DOMContentLoaded",j,!1),window.addEventListener("load",b.ready,!1);else if(l.attachEvent){l.attachEvent("onreadystatechange",j);window.attachEvent("onload",b.ready);var c=!1;try{c=null==window.frameElement}catch(d){}l.documentElement.doScroll&&
c&&a()}}},isFunction:function(a){return"function"===b.type(a)},isArray:Array.isArray||function(a){return"array"===b.type(a)},isWindow:function(a){return a&&"object"===typeof a&&"setInterval"in a},isNaN:function(a){return null==a||!t.test(a)||isNaN(a)},type:function(a){return null==a?""+a:x[q.call(a)]||"object"},isPlainObject:function(a){if(!a||"object"!==b.type(a)||a.nodeType||b.isWindow(a)||a.constructor&&!u.call(a,"constructor")&&!u.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(var c in a);
return void 0===c||u.call(a,c)},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw a;},parseJSON:function(a){if("string"!==typeof a||!a)return null;a=b.trim(a);if(n.test(a.replace(o,"@").replace(p,"]").replace(r,"")))return window.JSON&&window.JSON.parse?window.JSON.parse(a):(new Function("return "+a))();b.error("Invalid JSON: "+a)},noop:function(){},globalEval:function(a){if(a&&m.test(a)){var c=l.getElementsByTagName("head")[0]||l.documentElement,d=l.createElement("script");
d.type="text/javascript";b.support.scriptEval?d.appendChild(l.createTextNode(a)):d.text=a;c.insertBefore(d,c.firstChild);c.removeChild(d)}},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},each:function(a,c,d){var e,v=0,f=a.length,h=void 0===f||b.isFunction(a);if(d)if(h)for(e in a){if(!1===c.apply(a[e],d))break}else for(;v<f&&!(!1===c.apply(a[v++],d)););else if(h)for(e in a){if(!1===c.call(a[e],e,a[e]))break}else for(d=a[0];v<f&&!1!==c.call(d,v,d);d=a[++v]);return a},
trim:z?function(a){return null==a?"":z.call(a)}:function(a){return null==a?"":a.toString().replace(k,"").replace(w,"")},makeArray:function(a,c){var d=c||[];if(null!=a){var e=b.type(a);null==a.length||"string"===e||"function"===e||"regexp"===e||b.isWindow(a)?C.call(d,a):b.merge(d,a)}return d},inArray:function(a,b){if(b.indexOf)return b.indexOf(a);for(var c=0,d=b.length;c<d;c++)if(b[c]===a)return c;return-1},merge:function(a,b){var c=a.length,d=0;if("number"===typeof b.length)for(var e=b.length;d<e;d++)a[c++]=
b[d];else for(;void 0!==b[d];)a[c++]=b[d++];a.length=c;return a},grep:function(a,b,c){for(var d=[],e,c=!!c,v=0,f=a.length;v<f;v++)e=!!b(a[v],v),c!==e&&d.push(a[v]);return d},map:function(a,b,c){for(var d=[],e,v=0,f=a.length;v<f;v++)e=b(a[v],v,c),null!=e&&(d[d.length]=e);return d.concat.apply([],d)},guid:1,proxy:function(a,c,d){2===arguments.length&&("string"===typeof c?(d=a,a=d[c],c=void 0):c&&!b.isFunction(c)&&(d=c,c=void 0));!c&&a&&(c=function(){return a.apply(d||this,arguments)});if(a)c.guid=a.guid=
a.guid||c.guid||b.guid++;return c},access:function(a,c,d,e,v,f){var h=a.length;if("object"===typeof c){for(var k in c)b.access(a,k,c[k],e,v,d);return a}if(void 0!==d){e=!f&&e&&b.isFunction(d);for(k=0;k<h;k++)v(a[k],c,e?d.call(a[k],k,v(a[k],c)):d,f);return a}return h?v(a[0],c):void 0},now:function(){return(new Date).getTime()},uaMatch:function(a){a=a.toLowerCase();a=s.exec(a)||v.exec(a)||E.exec(a)||0>a.indexOf("compatible")&&ua.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),
function(a,b){x["[object "+b+"]"]=b.toLowerCase()});F=b.uaMatch(F);if(F.browser)b.browser[F.browser]=!0,b.browser.version=F.version;if(b.browser.webkit)b.browser.safari=!0;if(B)b.inArray=function(a,b){return B.call(b,a)};/\s/.test(" ")||(k=/^[\s\xA0]+/,w=/[\s\xA0]+$/);f=b(l);l.addEventListener?j=function(){l.removeEventListener("DOMContentLoaded",j,!1);b.ready()}:l.attachEvent&&(j=function(){"complete"===l.readyState&&(l.detachEvent("onreadystatechange",j),b.ready())});return window.jQuery=window.$=
b}();(function(){c.support={};var a=l.documentElement,b=l.createElement("script"),d=l.createElement("div"),e="script"+c.now();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var f=d.getElementsByTagName("*"),h=d.getElementsByTagName("a")[0],m=l.createElement("select"),k=m.appendChild(l.createElement("option"));if(f&&f.length&&h){c.support={leadingWhitespace:3===d.firstChild.nodeType,tbody:!d.getElementsByTagName("tbody").length,
htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(h.getAttribute("style")),hrefNormalized:"/a"===h.getAttribute("href"),opacity:/^0.55$/.test(h.style.opacity),cssFloat:!!h.style.cssFloat,checkOn:"on"===d.getElementsByTagName("input")[0].value,optSelected:k.selected,deleteExpando:!0,optDisabled:!1,checkClone:!1,scriptEval:!1,noCloneEvent:!0,boxModel:null,inlineBlockNeedsLayout:!1,shrinkWrapBlocks:!1,reliableHiddenOffsets:!0};m.disabled=!0;c.support.optDisabled=!k.disabled;b.type=
"text/javascript";try{b.appendChild(l.createTextNode("window."+e+"=1;"))}catch(w){}a.insertBefore(b,a.firstChild);if(window[e])c.support.scriptEval=!0,delete window[e];try{delete b.test}catch(g){c.support.deleteExpando=!1}a.removeChild(b);d.attachEvent&&d.fireEvent&&(d.attachEvent("onclick",function na(){c.support.noCloneEvent=!1;d.detachEvent("onclick",na)}),d.cloneNode(!0).fireEvent("onclick"));d=l.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=l.createDocumentFragment();
a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;c(function(){var a=l.createElement("div");a.style.width=a.style.paddingLeft="1px";l.body.appendChild(a);c.boxModel=c.support.boxModel=2===a.offsetWidth;if("zoom"in a.style)a.style.display="inline",a.style.zoom=1,c.support.inlineBlockNeedsLayout=2===a.offsetWidth,a.style.display="",a.innerHTML="<div style='width:4px;'></div>",c.support.shrinkWrapBlocks=2!==a.offsetWidth;a.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";
var b=a.getElementsByTagName("td");c.support.reliableHiddenOffsets=0===b[0].offsetHeight;b[0].style.display="";b[1].style.display="none";c.support.reliableHiddenOffsets=c.support.reliableHiddenOffsets&&0===b[0].offsetHeight;a.innerHTML="";l.body.removeChild(a).style.display="none"});a=function(a){var b=l.createElement("div"),a="on"+a,c=a in b;c||(b.setAttribute(a,"return;"),c="function"===typeof b[a]);return c};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=f=h=null}})();
var z={},x=/^(?:\{.*\}|\[.*\])$/;c.extend({cache:{},uuid:0,expando:"jQuery"+c.now(),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:!0},data:function(a,b,d){if(c.acceptData(a)){var a=a==window?z:a,e=a.nodeType,f=e?a[c.expando]:null,h=c.cache;if(!e||f||!("string"===typeof b&&void 0===d))return e?f||(a[c.expando]=f=++c.uuid):h=a,"object"===typeof b?e?h[f]=c.extend(h[f],b):c.extend(h,b):e&&!h[f]&&(h[f]={}),a=e?h[f]:h,void 0!==d&&(a[b]=d),"string"===typeof b?a[b]:a}},removeData:function(a,
b){if(c.acceptData(a)){var a=a==window?z:a,d=a.nodeType,e=d?a[c.expando]:a,f=c.cache,h=d?f[e]:e;if(b)h&&(delete h[b],d&&c.isEmptyObject(h)&&c.removeData(a));else if(d&&c.support.deleteExpando)delete a[c.expando];else if(a.removeAttribute)a.removeAttribute(c.expando);else if(d)delete f[e];else for(var m in a)delete a[m]}},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];if(b)return!(!0===b||a.getAttribute("classid")!==b)}return!0}});c.fn.extend({data:function(a,b){var d=
null;if("undefined"===typeof a){if(this.length)for(var e=this[0].attributes,f,d=c.data(this[0]),h=0,m=e.length;h<m;h++)f=e[h].name,0===f.indexOf("data-")&&(f=f.substr(5),j(this[0],f,d[f]));return d}if("object"===typeof a)return this.each(function(){c.data(this,a)});var k=a.split(".");k[1]=k[1]?"."+k[1]:"";return void 0===b?(d=this.triggerHandler("getData"+k[1]+"!",[k[0]]),void 0===d&&this.length&&(d=c.data(this[0],a),d=j(this[0],a,d)),void 0===d&&k[1]?this.data(k[0]):d):this.each(function(){var d=
c(this),e=[k[0],b];d.triggerHandler("setData"+k[1]+"!",e);c.data(this,a,b);d.triggerHandler("changeData"+k[1]+"!",e)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){var b=(b||"fx")+"queue",e=c.data(a,b);if(!d)return e||[];!e||c.isArray(d)?e=c.data(a,b,c.makeArray(d)):e.push(d);return e}},dequeue:function(a,b){var b=b||"fx",d=c.queue(a,b),e=d.shift();"inprogress"===e&&(e=d.shift());e&&("fx"===b&&d.unshift("inprogress"),e.call(a,
function(){c.dequeue(a,b)}))}});c.fn.extend({queue:function(a,b){"string"!==typeof a&&(b=a,a="fx");return void 0===b?c.queue(this[0],a):this.each(function(){var d=c.queue(this,a,b);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});
var V=/[\n\t]/g,Q=/\s+/,va=/\r/g,wa=/^(?:href|src|style)$/,xa=/^(?:button|input)$/i,ya=/^(?:button|input|object|select|textarea)$/i,za=/^a(?:rea)?$/i,W=/^(?:radio|checkbox)$/i;c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};c.fn.extend({attr:function(a,b){return c.access(this,a,b,!0,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,
a,"");1===this.nodeType&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.addClass(a.call(this,b,d.attr("class")))});if(a&&"string"===typeof a)for(var b=(a||"").split(Q),d=0,e=this.length;d<e;d++){var f=this[d];if(1===f.nodeType)if(f.className){for(var h=" "+f.className+" ",m=f.className,k=0,w=b.length;k<w;k++)0>h.indexOf(" "+b[k]+" ")&&(m+=" "+b[k]);f.className=c.trim(m)}else f.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(b){var d=
c(this);d.removeClass(a.call(this,b,d.attr("class")))});if(a&&"string"===typeof a||void 0===a)for(var b=(a||"").split(Q),d=0,e=this.length;d<e;d++){var f=this[d];if(1===f.nodeType&&f.className)if(a){for(var h=(" "+f.className+" ").replace(V," "),m=0,k=b.length;m<k;m++)h=h.replace(" "+b[m]+" "," ");f.className=c.trim(h)}else f.className=""}return this},toggleClass:function(a,b){var d=typeof a,e="boolean"===typeof b;return c.isFunction(a)?this.each(function(d){var e=c(this);e.toggleClass(a.call(this,
d,e.attr("class"),b),b)}):this.each(function(){if("string"===d)for(var f,h=0,m=c(this),k=b,w=a.split(Q);f=w[h++];)k=e?k:!m.hasClass(f),m[k?"addClass":"removeClass"](f);else if("undefined"===d||"boolean"===d)this.className&&c.data(this,"__className__",this.className),this.className=this.className||!1===a?"":c.data(this,"__className__")||""})},hasClass:function(a){for(var a=" "+a+" ",b=0,c=this.length;b<c;b++)if(-1<(" "+this[b].className+" ").replace(V," ").indexOf(a))return!0;return!1},val:function(a){if(arguments.length){var b=
c.isFunction(a);return this.each(function(d){var e=c(this),f=a;if(1===this.nodeType)if(b&&(f=a.call(this,d,e.val())),null==f?f="":"number"===typeof f?f+="":c.isArray(f)&&(f=c.map(f,function(a){return null==a?"":a+""})),c.isArray(f)&&W.test(this.type))this.checked=0<=c.inArray(e.val(),f);else if(c.nodeName(this,"select")){var h=c.makeArray(f);c("option",this).each(function(){this.selected=0<=c.inArray(c(this).val(),h)});if(!h.length)this.selectedIndex=-1}else this.value=f})}var d=this[0];if(d){if(c.nodeName(d,
"option")){var e=d.attributes.value;return!e||e.specified?d.value:d.text}if(c.nodeName(d,"select")){var f=d.selectedIndex,e=[],h=d.options,d="select-one"===d.type;if(0>f)return null;for(var m=d?f:0,f=d?f+1:h.length;m<f;m++){var k=h[m];if(k.selected&&(c.support.optDisabled?!k.disabled:null===k.getAttribute("disabled"))&&(!k.parentNode.disabled||!c.nodeName(k.parentNode,"optgroup"))){a=c(k).val();if(d)return a;e.push(a)}}return e}return W.test(d.type)&&!c.support.checkOn?null===d.getAttribute("value")?
"on":d.value:(d.value||"").replace(va,"")}}});c.extend({attrFn:{val:!0,css:!0,html:!0,text:!0,data:!0,width:!0,height:!0,offset:!0},attr:function(a,b,d,e){if(a&&!(3===a.nodeType||8===a.nodeType)){if(e&&b in c.attrFn)return c(a)[b](d);var e=1!==a.nodeType||!c.isXMLDoc(a),f=void 0!==d,b=e&&c.props[b]||b,h=wa.test(b);if((b in a||void 0!==a[b])&&e&&!h){f&&("type"===b&&xa.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed"),null===d?1===a.nodeType&&a.removeAttribute(b):a[b]=d);if(c.nodeName(a,
"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;return"tabIndex"===b?(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:ya.test(a.nodeName)||za.test(a.nodeName)&&a.href?0:void 0:a[b]}if(!c.support.style&&e&&"style"===b){if(f)a.style.cssText=""+d;return a.style.cssText}f&&a.setAttribute(b,""+d);if(a.attributes[b]||!a.hasAttribute||a.hasAttribute(b))return a=!c.support.hrefNormalized&&e&&h?a.getAttribute(b,2):a.getAttribute(b),null===a?void 0:a}}});var K=/\.(.*)$/,R=/^(?:textarea|input|select)$/i,
oa=/\./g,pa=/ /g,Aa=/[^\w\s.|`]/g,Ba=function(a){return a.replace(Aa,"\\$&")},X={focusin:0,focusout:0};c.event={add:function(a,b,d,e){if(!(3===a.nodeType||8===a.nodeType)){c.isWindow(a)&&a!==window&&!a.frameElement&&(a=window);if(!1===d)d=r;else if(!d)return;var f,h;if(d.handler)f=d,d=f.handler;if(!d.guid)d.guid=c.guid++;if(h=c.data(a)){var m=a.nodeType?"events":"__events__",k=h[m],w=h.handle;if("function"===typeof k)w=k.handle,k=k.events;else if(!k)a.nodeType||(h[m]=h=function(){}),h.events=k={};
if(!w)h.handle=w=function(){return"undefined"!==typeof c&&!c.event.triggered?c.event.handle.apply(w.elem,arguments):void 0};w.elem=a;for(var b=b.split(" "),g=0,l;m=b[g++];){h=f?c.extend({},f):{handler:d,data:e};-1<m.indexOf(".")?(l=m.split("."),m=l.shift(),h.namespace=l.slice(0).sort().join(".")):(l=[],h.namespace="");h.type=m;if(!h.guid)h.guid=d.guid;var t=k[m],i=c.event.special[m]||{};if(!t&&(t=k[m]=[],!i.setup||!1===i.setup.call(a,e,l,w)))a.addEventListener?a.addEventListener(m,w,!1):a.attachEvent&&
a.attachEvent("on"+m,w);if(i.add&&(i.add.call(a,h),!h.handler.guid))h.handler.guid=d.guid;t.push(h);c.event.global[m]=!0}a=null}}},global:{},remove:function(a,b,d,e){if(!(3===a.nodeType||8===a.nodeType)){!1===d&&(d=r);var f,h,m=0,k,w,g,l,t,i,n=a.nodeType?"events":"__events__",o=c.data(a),p=o&&o[n];if(o&&p){if("function"===typeof p)o=p,p=p.events;if(b&&b.type)d=b.handler,b=b.type;if(!b||"string"===typeof b&&"."===b.charAt(0))for(f in b=b||"",p)c.event.remove(a,f+b);else{for(b=b.split(" ");f=b[m++];)if(l=
f,k=0>f.indexOf("."),w=[],k||(w=f.split("."),f=w.shift(),g=RegExp("(^|\\.)"+c.map(w.slice(0).sort(),Ba).join("\\.(?:.*\\.)?")+"(\\.|$)")),t=p[f])if(d){l=c.event.special[f]||{};for(h=e||0;h<t.length;h++)if(i=t[h],d.guid===i.guid){if(k||g.test(i.namespace))null==e&&t.splice(h--,1),l.remove&&l.remove.call(a,i);if(null!=e)break}if(0===t.length||null!=e&&1===t.length)(!l.teardown||!1===l.teardown.call(a,w))&&c.removeEvent(a,f,o.handle),delete p[f]}else for(h=0;h<t.length;h++)if(i=t[h],k||g.test(i.namespace))c.event.remove(a,
l,i.handler,h),t.splice(h--,1);if(c.isEmptyObject(p)){if(b=o.handle)b.elem=null;delete o.events;delete o.handle;"function"===typeof o?c.removeData(a,n):c.isEmptyObject(o)&&c.removeData(a)}}}}},trigger:function(a,b,d,e){var f=a.type||a;if(!e){a="object"===typeof a?a[c.expando]?a:c.extend(c.Event(f),a):c.Event(f);if(0<=f.indexOf("!"))a.type=f=f.slice(0,-1),a.exclusive=!0;d||(a.stopPropagation(),c.event.global[f]&&c.each(c.cache,function(){this.events&&this.events[f]&&c.event.trigger(a,b,this.handle.elem)}));
if(!d||3===d.nodeType||8===d.nodeType)return;a.result=void 0;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(e=d.nodeType?c.data(d,"handle"):(c.data(d,"__events__")||{}).handle)&&e.apply(d,b);e=d.parentNode||d.ownerDocument;try{if((!d||!d.nodeName||!c.noData[d.nodeName.toLowerCase()])&&d["on"+f]&&!1===d["on"+f].apply(d,b))a.result=!1,a.preventDefault()}catch(h){}if(!a.isPropagationStopped()&&e)c.event.trigger(a,b,e,!0);else if(!a.isDefaultPrevented()){var m,e=a.target,k=f.replace(K,""),
w=c.nodeName(e,"a")&&"click"===k,g=c.event.special[k]||{};if((!g._default||!1===g._default.call(d,a))&&!w&&(!e||!e.nodeName||!c.noData[e.nodeName.toLowerCase()])){try{if(e[k])(m=e["on"+k])&&(e["on"+k]=null),c.event.triggered=!0,e[k]()}catch(l){}m&&(e["on"+k]=m);c.event.triggered=!1}}},handle:function(a){var b,d,e,f;d=[];var h=c.makeArray(arguments),a=h[0]=c.event.fix(a||window.event);a.currentTarget=this;b=0>a.type.indexOf(".")&&!a.exclusive;if(!b)e=a.type.split("."),a.type=e.shift(),d=e.slice(0).sort(),
e=RegExp("(^|\\.)"+d.join("\\.(?:.*\\.)?")+"(\\.|$)");a.namespace=a.namespace||d.join(".");f=c.data(this,this.nodeType?"events":"__events__");if("function"===typeof f)f=f.events;d=(f||{})[a.type];if(f&&d){d=d.slice(0);f=0;for(var m=d.length;f<m;f++){var k=d[f];if(b||e.test(k.namespace)){a.handler=k.handler;a.data=k.data;a.handleObj=k;k=k.handler.apply(this,h);if(void 0!==k)a.result=k,!1===k&&(a.preventDefault(),a.stopPropagation());if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[c.expando])return a;for(var b=a,a=c.Event(b),d=this.props.length,e;d;)e=this.props[--d],a[e]=b[e];if(!a.target)a.target=a.srcElement||l;if(3===a.target.nodeType)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(null==a.pageX&&null!=a.clientX)b=l.documentElement,d=l.body,a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0),a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0);if(null==a.which&&(null!=a.charCode||null!=a.keyCode))a.which=null!=a.charCode?a.charCode:a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&void 0!==a.button)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,s(a.origType,a.selector),c.extend({},a,{handler:p,guid:a.handler.guid}))},remove:function(a){c.event.remove(this,
s(a.origType,a.selector),a)}},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};c.removeEvent=l.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)}:function(a,b,c){a.detachEvent&&a.detachEvent("on"+b,c)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);a&&a.type?(this.originalEvent=a,this.type=a.type):this.type=a;this.timeStamp=c.now();
this[c.expando]=!0};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=q;var a=this.originalEvent;if(a)a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(){this.isPropagationStopped=q;var a=this.originalEvent;if(a)a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=q;this.stopPropagation()},isDefaultPrevented:r,isPropagationStopped:r,isImmediatePropagationStopped:r};var Y=function(a){var b=
a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this)a.type=a.data,c.event.handle.apply(this,arguments)}catch(d){}},Z=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Z:Y,a)},teardown:function(a){c.event.remove(this,b,a&&a.selector?Z:Y)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if("form"!==this.nodeName.toLowerCase())c.event.add(this,
"click.specialSubmit",function(a){var b=a.target,d=b.type;if(("submit"===d||"image"===d)&&c(b).closest("form").length)return a.liveFired=void 0,o("submit",this,arguments)}),c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if(("text"===d||"password"===d)&&c(b).closest("form").length&&13===a.keyCode)return a.liveFired=void 0,o("submit",this,arguments)});else return!1},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var I,aa=function(a){var b=
a.type,d=a.value;if("radio"===b||"checkbox"===b)d=a.checked;else if("select-multiple"===b)d=-1<a.selectedIndex?c.map(a.options,function(a){return a.selected}).join("-"):"";else if("select"===a.nodeName.toLowerCase())d=a.selectedIndex;return d},L=function(a,b){var d=a.target,e,f;if(R.test(d.nodeName)&&!d.readOnly&&(e=c.data(d,"_change_data"),f=aa(d),("focusout"!==a.type||"radio"!==d.type)&&c.data(d,"_change_data",f),!(void 0===e||f===e)))if(null!=e||f)return a.type="change",a.liveFired=void 0,c.event.trigger(a,
b,d)};c.event.special.change={filters:{focusout:L,beforedeactivate:L,click:function(a){var b=a.target,c=b.type;if("radio"===c||"checkbox"===c||"select"===b.nodeName.toLowerCase())return L.call(this,a)},keydown:function(a){var b=a.target,c=b.type;if(13===a.keyCode&&"textarea"!==b.nodeName.toLowerCase()||32===a.keyCode&&("checkbox"===c||"radio"===c)||"select-multiple"===c)return L.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",aa(a))}},setup:function(){if("file"===this.type)return!1;
for(var a in I)c.event.add(this,a+".specialChange",I[a]);return R.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return R.test(this.nodeName)}};I=c.event.special.change.filters;I.focus=I.beforeactivate}l.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(a){a=c.event.fix(a);a.type=b;return c.event.trigger(a,null,a.target)}c.event.special[b]={setup:function(){0===X[b]++&&l.addEventListener(a,d,!0)},teardown:function(){0===--X[b]&&l.removeEventListener(a,
d,!0)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(a,e,f){if("object"===typeof a){for(var h in a)this[b](h,e,a[h],f);return this}if(c.isFunction(e)||!1===e)f=e,e=void 0;var m="one"===b?c.proxy(f,function(a){c(this).unbind(a,m);return f.apply(this,arguments)}):f;if("unload"===a&&"one"!==b)this.one(a,e,f);else{h=0;for(var k=this.length;h<k;h++)c.event.add(this[h],a,m,e)}return this}});c.fn.extend({unbind:function(a,b){if("object"===typeof a&&!a.preventDefault)for(var d in a)this.unbind(d,
a[d]);else{d=0;for(var e=this.length;d<e;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,c,e){return this.live(b,c,e,a)},undelegate:function(a,b,c){return 0===arguments.length?this.unbind("live"):this.die(b,null,c,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){var d=c.Event(a);d.preventDefault();d.stopPropagation();c.event.trigger(d,b,this[0]);return d.result}},toggle:function(a){for(var b=arguments,d=
1;d<b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,function(e){var f=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,f+1);e.preventDefault();return b[f].apply(this,arguments)||!1}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var ba={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(a,e,f,h){var m,k=0,g,l,t=h||this.selector,h=h?this:c(this.context);if("object"===
typeof a&&!a.preventDefault){for(m in a)h[b](m,e,a[m],t);return this}c.isFunction(e)&&(f=e,e=void 0);for(a=(a||"").split(" ");null!=(m=a[k++]);)if(g=K.exec(m),l="",g&&(l=g[0],m=m.replace(K,"")),"hover"===m)a.push("mouseenter"+l,"mouseleave"+l);else if(g=m,"focus"===m||"blur"===m?(a.push(ba[m]+l),m+=l):m=(ba[m]||m)+l,"live"===b){l=0;for(var i=h.length;l<i;l++)c.event.add(h[l],"live."+s(m,t),{data:e,selector:t,handler:f,origType:m,origHandler:f,preType:g})}else h.unbind("live."+s(m,t),f);return this}});
c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),function(a,b){c.fn[b]=function(a,c){null==c&&(c=a,a=null);return 0<arguments.length?this.bind(b,a,c):this.trigger(b)};c.attrFn&&(c.attrFn[b]=!0)});window.attachEvent&&!window.addEventListener&&c(window).bind("unload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});
(function(){function a(a,b,c,d,e,f){for(var e=0,h=d.length;e<h;e++){var k=d[e];if(k){for(var g=!1,k=k[a];k;){if(k.sizcache===c){g=d[k.sizset];break}if(1===k.nodeType&&!f)k.sizcache=c,k.sizset=e;if(k.nodeName.toLowerCase()===b){g=k;break}k=k[a]}d[e]=g}}}function b(a,b,c,d,e,f){for(var e=0,h=d.length;e<h;e++){var g=d[e];if(g){for(var m=!1,g=g[a];g;){if(g.sizcache===c){m=d[g.sizset];break}if(1===g.nodeType){if(!f)g.sizcache=c,g.sizset=e;if("string"!==typeof b){if(g===b){m=!0;break}}else if(0<k.filter(b,
[g]).length){m=g;break}}g=g[a]}d[e]=m}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,f=Object.prototype.toString,h=!1,m=!0;[0,0].sort(function(){m=!1;return 0});var k=function(a,b,c,e){var c=c||[],h=b=b||l;if(1!==b.nodeType&&9!==b.nodeType)return[];if(!a||"string"!==typeof a)return c;var m,i,n,p,j,r=!0,u=k.isXML(b),q=[],C=a;do if(d.exec(""),m=d.exec(C))if(C=m[3],q.push(m[1]),m[2]){p=m[3];break}while(m);
if(1<q.length&&t.exec(a))if(2===q.length&&g.relative[q[0]])i=s(q[0]+q[1],b);else for(i=g.relative[q[0]]?[b]:k(q.shift(),b);q.length;)a=q.shift(),g.relative[a]&&(a+=q.shift()),i=s(a,i);else if(!e&&1<q.length&&9===b.nodeType&&!u&&g.match.ID.test(q[0])&&!g.match.ID.test(q[q.length-1])&&(m=k.find(q.shift(),b,u),b=m.expr?k.filter(m.expr,m.set)[0]:m.set[0]),b){m=e?{expr:q.pop(),set:o(e)}:k.find(q.pop(),1===q.length&&("~"===q[0]||"+"===q[0])&&b.parentNode?b.parentNode:b,u);i=m.expr?k.filter(m.expr,m.set):
m.set;for(0<q.length?n=o(i):r=!1;q.length;)m=j=q.pop(),g.relative[j]?m=q.pop():j="",null==m&&(m=b),g.relative[j](n,m,u)}else n=[];n||(n=i);n||k.error(j||a);if("[object Array]"===f.call(n))if(r)if(b&&1===b.nodeType)for(a=0;null!=n[a];a++)n[a]&&(!0===n[a]||1===n[a].nodeType&&k.contains(b,n[a]))&&c.push(i[a]);else for(a=0;null!=n[a];a++)n[a]&&1===n[a].nodeType&&c.push(i[a]);else c.push.apply(c,n);else o(n,c);p&&(k(p,h,c,e),k.uniqueSort(c));return c};k.uniqueSort=function(a){if(j&&(h=m,a.sort(j),h))for(var b=
1;b<a.length;b++)a[b]===a[b-1]&&a.splice(b--,1);return a};k.matches=function(a,b){return k(a,null,null,b)};k.matchesSelector=function(a,b){return 0<k(b,null,null,[a]).length};k.find=function(a,b,c){var d;if(!a)return[];for(var e=0,f=g.order.length;e<f;e++){var h,k=g.order[e];if(h=g.leftMatch[k].exec(a)){var m=h[1];h.splice(1,1);if("\\"!==m.substr(m.length-1)&&(h[1]=(h[1]||"").replace(/\\/g,""),d=g.find[k](h,b,c),null!=d)){a=a.replace(g.match[k],"");break}}}d||(d=b.getElementsByTagName("*"));return{set:d,
expr:a}};k.filter=function(a,b,c,d){for(var e,f,h=a,m=[],l=b,t=b&&b[0]&&k.isXML(b[0]);a&&b.length;){for(var i in g.filter)if(null!=(e=g.leftMatch[i].exec(a))&&e[2]){var n,o,q=g.filter[i];o=e[1];f=!1;e.splice(1,1);if("\\"!==o.substr(o.length-1)){l===m&&(m=[]);if(g.preFilter[i])if(e=g.preFilter[i](e,l,c,m,d,t)){if(!0===e)continue}else f=n=!0;if(e)for(var p=0;null!=(o=l[p]);p++)if(o){n=q(o,e,p,l);var j=d^!!n;c&&null!=n?j?f=!0:l[p]=!1:j&&(m.push(o),f=!0)}if(void 0!==n){c||(l=m);a=a.replace(g.match[i],
"");if(!f)return[];break}}}if(a===h)if(null==f)k.error(a);else break;h=a}return l};k.error=function(a){throw"Syntax error, unrecognized expression: "+a;};var g=k.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,
POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")}},relative:{"+":function(a,b){var c="string"===typeof b,d=c&&!/\W/.test(b),c=c&&!d;d&&(b=b.toLowerCase());for(var d=0,e=a.length,f;d<e;d++)if(f=a[d]){for(;(f=f.previousSibling)&&1!==f.nodeType;);a[d]=c||f&&f.nodeName.toLowerCase()===
b?f||!1:f===b}c&&k.filter(b,a,!0)},">":function(a,b){var c,d="string"===typeof b,e=0,f=a.length;if(d&&!/\W/.test(b))for(b=b.toLowerCase();e<f;e++){if(c=a[e])c=c.parentNode,a[e]=c.nodeName.toLowerCase()===b?c:!1}else{for(;e<f;e++)(c=a[e])&&(a[e]=d?c.parentNode:c.parentNode===b);d&&k.filter(b,a,!0)}},"":function(c,d,f){var h,k=e++,m=b;"string"===typeof d&&!/\W/.test(d)&&(h=d=d.toLowerCase(),m=a);m("parentNode",d,k,c,h,f)},"~":function(c,d,f){var h,k=e++,m=b;"string"===typeof d&&!/\W/.test(d)&&(h=d=
d.toLowerCase(),m=a);m("previousSibling",d,k,c,h,f)}},find:{ID:function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(a=b.getElementById(a[1]))&&a.parentNode?[a]:[]},NAME:function(a,b){if("undefined"!==typeof b.getElementsByName){for(var c=[],d=b.getElementsByName(a[1]),e=0,f=d.length;e<f;e++)d[e].getAttribute("name")===a[1]&&c.push(d[e]);return 0===c.length?null:c}},TAG:function(a,b){return b.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,b,c,d,e,f){a=" "+a[1].replace(/\\/g,
"")+" ";if(f)return a;for(var f=0,h;null!=(h=b[f]);f++)h&&(e^(h.className&&0<=(" "+h.className+" ").replace(/[\t\n]/g," ").indexOf(a))?c||d.push(h):c&&(b[f]=!1));return!1},ID:function(a){return a[1].replace(/\\/g,"")},TAG:function(a){return a[1].toLowerCase()},CHILD:function(a){if("nth"===a[1]){var b=/(-?)(\d*)n((?:\+|-)?\d*)/.exec("even"===a[2]&&"2n"||"odd"===a[2]&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=b[1]+(b[2]||1)-0;a[3]=b[3]-0}a[0]=e++;return a},ATTR:function(a,b,c,d,e,f){b=a[1].replace(/\\/g,
"");!f&&g.attrMap[b]&&(a[1]=g.attrMap[b]);"~="===a[2]&&(a[4]=" "+a[4]+" ");return a},PSEUDO:function(a,b,c,e,f){if("not"===a[1])if(1<(d.exec(a[3])||"").length||/^\w/.test(a[3]))a[3]=k(a[3],null,null,b);else return a=k.filter(a[3],b,c,1^f),c||e.push.apply(e,a),!1;else if(g.match.POS.test(a[0])||g.match.CHILD.test(a[0]))return!0;return a},POS:function(a){a.unshift(!0);return a}},filters:{enabled:function(a){return!1===a.disabled&&"hidden"!==a.type},disabled:function(a){return!0===a.disabled},checked:function(a){return!0===
a.checked},selected:function(a){return!0===a.selected},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},has:function(a,b,c){return!!k(c[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},text:function(a){return"text"===a.type},radio:function(a){return"radio"===a.type},checkbox:function(a){return"checkbox"===a.type},file:function(a){return"file"===a.type},password:function(a){return"password"===a.type},submit:function(a){return"submit"===a.type},image:function(a){return"image"===
a.type},reset:function(a){return"reset"===a.type},button:function(a){return"button"===a.type||"button"===a.nodeName.toLowerCase()},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)}},setFilters:{first:function(a,b){return 0===b},last:function(a,b,c,d){return b===d.length-1},even:function(a,b){return 0===b%2},odd:function(a,b){return 1===b%2},lt:function(a,b,c){return b<c[3]-0},gt:function(a,b,c){return b>c[3]-0},nth:function(a,b,c){return c[3]-0===b},eq:function(a,b,c){return c[3]-
0===b}},filter:{PSEUDO:function(a,b,c,d){var e=b[1],f=g.filters[e];if(f)return f(a,c,b,d);if("contains"===e)return 0<=(a.textContent||a.innerText||k.getText([a])||"").indexOf(b[3]);if("not"===e){b=b[3];c=0;for(d=b.length;c<d;c++)if(b[c]===a)return!1;return!0}k.error("Syntax error, unrecognized expression: "+e)},CHILD:function(a,b){var c=b[1],d=a;switch(c){case "only":case "first":for(;d=d.previousSibling;)if(1===d.nodeType)return!1;if("first"===c)return!0;d=a;case "last":for(;d=d.nextSibling;)if(1===
d.nodeType)return!1;return!0;case "nth":var c=b[2],e=b[3];if(1===c&&0===e)return!0;var f=b[0],h=a.parentNode;if(h&&(h.sizcache!==f||!a.nodeIndex)){for(var k=0,d=h.firstChild;d;d=d.nextSibling)if(1===d.nodeType)d.nodeIndex=++k;h.sizcache=f}d=a.nodeIndex-e;return 0===c?0===d:0===d%c&&0<=d/c}},ID:function(a,b){return 1===a.nodeType&&a.getAttribute("id")===b},TAG:function(a,b){return"*"===b&&1===a.nodeType||a.nodeName.toLowerCase()===b},CLASS:function(a,b){return-1<(" "+(a.className||a.getAttribute("class"))+
" ").indexOf(b)},ATTR:function(a,b){var c=b[1],c=g.attrHandle[c]?g.attrHandle[c](a):null!=a[c]?a[c]:a.getAttribute(c),d=c+"",e=b[2],f=b[4];return null==c?"!="===e:"="===e?d===f:"*="===e?0<=d.indexOf(f):"~="===e?0<=(" "+d+" ").indexOf(f):!f?d&&!1!==c:"!="===e?d!==f:"^="===e?0===d.indexOf(f):"$="===e?d.substr(d.length-f.length)===f:"|="===e?d===f||d.substr(0,f.length+1)===f+"-":!1},POS:function(a,b,c,d){var e=g.setFilters[b[2]];if(e)return e(a,c,b,d)}}},t=g.match.POS,i=function(a,b){return"\\"+(b-0+
1)},n;for(n in g.match)g.match[n]=RegExp(g.match[n].source+/(?![^\[]*\])(?![^\(]*\))/.source),g.leftMatch[n]=RegExp(/(^(?:.|\r|\n)*?)/.source+g.match[n].source.replace(/\\(\d+)/g,i));var o=function(a,b){a=Array.prototype.slice.call(a,0);return b?(b.push.apply(b,a),b):a};try{Array.prototype.slice.call(l.documentElement.childNodes,0)}catch(p){o=function(a,b){var c=0,d=b||[];if("[object Array]"===f.call(a))Array.prototype.push.apply(d,a);else if("number"===typeof a.length)for(var e=a.length;c<e;c++)d.push(a[c]);
else for(;a[c];c++)d.push(a[c]);return d}}var j,r;l.documentElement.compareDocumentPosition?j=function(a,b){return a===b?(h=!0,0):!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?-1:1:a.compareDocumentPosition(b)&4?-1:1}:(j=function(a,b){var c,d,e=[],f=[];c=a.parentNode;d=b.parentNode;var k=c;if(a===b)return h=!0,0;if(c===d)return r(a,b);if(c){if(!d)return 1}else return-1;for(;k;)e.unshift(k),k=k.parentNode;for(k=d;k;)f.unshift(k),k=k.parentNode;c=e.length;d=f.length;
for(k=0;k<c&&k<d;k++)if(e[k]!==f[k])return r(e[k],f[k]);return k===c?r(a,f[k],-1):r(e[k],b,1)},r=function(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});k.getText=function(a){for(var b="",c,d=0;a[d];d++)c=a[d],3===c.nodeType||4===c.nodeType?b+=c.nodeValue:8!==c.nodeType&&(b+=k.getText(c.childNodes));return b};(function(){var a=l.createElement("div"),b="script"+(new Date).getTime(),c=l.documentElement;a.innerHTML="<a name='"+b+"'/>";c.insertBefore(a,c.firstChild);
if(l.getElementById(b))g.find.ID=function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(b=b.getElementById(a[1]))?b.id===a[1]||"undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id").nodeValue===a[1]?[b]:void 0:[]},g.filter.ID=function(a,b){var c="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id");return 1===a.nodeType&&c&&c.nodeValue===b};c.removeChild(a);c=a=null})();(function(){var a=l.createElement("div");a.appendChild(l.createComment(""));if(0<a.getElementsByTagName("*").length)g.find.TAG=
function(a,b){var c=b.getElementsByTagName(a[1]);if("*"===a[1]){for(var d=[],e=0;c[e];e++)1===c[e].nodeType&&d.push(c[e]);c=d}return c};a.innerHTML="<a href='#'></a>";if(a.firstChild&&"undefined"!==typeof a.firstChild.getAttribute&&"#"!==a.firstChild.getAttribute("href"))g.attrHandle.href=function(a){return a.getAttribute("href",2)};a=null})();l.querySelectorAll&&function(){var a=k,b=l.createElement("div");b.innerHTML="<p class='TEST'></p>";if(!(b.querySelectorAll&&0===b.querySelectorAll(".TEST").length)){k=
function(b,c,d,e){c=c||l;b=b.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!e&&!k.isXML(c))if(9===c.nodeType)try{return o(c.querySelectorAll(b),d)}catch(f){}else if(1===c.nodeType&&"object"!==c.nodeName.toLowerCase()){var h=c.getAttribute("id"),m=h||"__sizzle__";h||c.setAttribute("id",m);try{return o(c.querySelectorAll("#"+m+" "+b),d)}catch(g){}finally{h||c.removeAttribute("id")}}return a(b,c,d,e)};for(var c in a)k[c]=a[c];b=null}}();(function(){var a=l.documentElement,b=a.matchesSelector||a.mozMatchesSelector||
a.webkitMatchesSelector||a.msMatchesSelector,c=!1;try{b.call(l.documentElement,"[test!='']:sizzle")}catch(d){c=!0}if(b)k.matchesSelector=function(a,d){d=d.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!k.isXML(a))try{if(c||!g.match.PSEUDO.test(d)&&!/!=/.test(d))return b.call(a,d)}catch(e){}return 0<k(d,null,null,[a]).length}})();(function(){var a=l.createElement("div");a.innerHTML="<div class='test e'></div><div class='test'></div>";if(a.getElementsByClassName&&0!==a.getElementsByClassName("e").length&&
(a.lastChild.className="e",1!==a.getElementsByClassName("e").length))g.order.splice(1,0,"CLASS"),g.find.CLASS=function(a,b,c){if("undefined"!==typeof b.getElementsByClassName&&!c)return b.getElementsByClassName(a[1])},a=null})();k.contains=l.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):!0)}:l.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:function(){return!1};k.isXML=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?
"HTML"!==a.nodeName:!1};var s=function(a,b){for(var c,d=[],e="",f=b.nodeType?[b]:b;c=g.match.PSEUDO.exec(a);)e+=c[0],a=a.replace(g.match.PSEUDO,"");a=g.relative[a]?a+"*":a;c=0;for(var h=f.length;c<h;c++)k(a,f[c],d);return k.filter(e,d)};c.find=k;c.expr=k.selectors;c.expr[":"]=c.expr.filters;c.unique=k.uniqueSort;c.text=k.getText;c.isXMLDoc=k.isXML;c.contains=k.contains})();var Ca=/Until$/,Da=/^(?:parents|prevUntil|prevAll)/,Ea=/,/,qa=/^.[^:#\[\.,]*$/,Fa=Array.prototype.slice,Ga=c.expr.match.POS;c.fn.extend({find:function(a){for(var b=
this.pushStack("","find",a),d=0,e=0,f=this.length;e<f;e++)if(d=b.length,c.find(a,this[e],b),0<e)for(var h=d;h<b.length;h++)for(var m=0;m<d;m++)if(b[m]===b[h]){b.splice(h--,1);break}return b},has:function(a){var b=c(a);return this.filter(function(){for(var a=0,e=b.length;a<e;a++)if(c.contains(this,b[a]))return!0})},not:function(a){return this.pushStack(u(this,a,!1),"not",a)},filter:function(a){return this.pushStack(u(this,a,!0),"filter",a)},is:function(a){return!!a&&0<c.filter(a,this).length},closest:function(a,
b){var d=[],e,f,h=this[0];if(c.isArray(a)){var m,k={},g=1;if(h&&a.length){for(e=0,f=a.length;e<f;e++)m=a[e],k[m]||(k[m]=c.expr.match.POS.test(m)?c(m,b||this.context):m);for(;h&&h.ownerDocument&&h!==b;){for(m in k)e=k[m],(e.jquery?-1<e.index(h):c(h).is(e))&&d.push({selector:m,elem:h,level:g});h=h.parentNode;g++}}return d}m=Ga.test(a)?c(a,b||this.context):null;for(e=0,f=this.length;e<f;e++)for(h=this[e];h;)if(m?-1<m.index(h):c.find.matchesSelector(h,a)){d.push(h);break}else if(h=h.parentNode,!h||!h.ownerDocument||
h===b)break;d=1<d.length?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){return!a||"string"===typeof a?c.inArray(this[0],a?c(a):this.parent().children()):c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){var d="string"===typeof a?c(a,b||this.context):c.makeArray(a),e=c.merge(this.get(),d);return this.pushStack(!d[0]||!d[0].parentNode||11===d[0].parentNode.nodeType||!e[0]||!e[0].parentNode||11===e[0].parentNode.nodeType?e:c.unique(e))},andSelf:function(){return this.add(this.prevObject)}});
c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",
d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);Ca.test(a)||(e=d);e&&"string"===typeof e&&(f=c.filter(e,f));f=1<this.length?c.unique(f):f;if((1<this.length||Ea.test(e))&&Da.test(a))f=f.reverse();return this.pushStack(f,a,Fa.call(arguments).join(","))}});
c.extend({filter:function(a,b,d){d&&(a=":not("+a+")");return 1===b.length?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){for(var e=[],a=a[b];a&&9!==a.nodeType&&(void 0===d||1!==a.nodeType||!c(a).is(d));)1===a.nodeType&&e.push(a),a=a[b];return e},nth:function(a,b,c){for(var b=b||1,e=0;a&&!(1===a.nodeType&&++e===b);a=a[c]);return a},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});var ca=/ jQuery\d+="(?:\d+|null)"/g,
M=/^\s+/,da=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,ea=/<([\w:]+)/,Ha=/<tbody/i,Ia=/<|&#?\w+;/,fa=/<(?:script|object|embed|option|style)/i,ga=/checked\s*(?:[^=]|=\s*.checked.)/i,Ja=/\=([^="'>\s]+\/)>/g,A={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],
area:[1,"<map>","</map>"],_default:[0,"",""]};A.optgroup=A.option;A.tbody=A.tfoot=A.colgroup=A.caption=A.thead;A.th=A.td;if(!c.support.htmlSerialize)A._default=[1,"div<div>","</div>"];c.fn.extend({text:function(a){return c.isFunction(a)?this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))}):"object"!==typeof a&&void 0!==a?this.empty().append((this[0]&&this[0].ownerDocument||l).createTextNode(a)):c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapAll(a.call(this,
b))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&1===a.firstChild.nodeType;)a=a.firstChild;return a}).append(this)}return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,
"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,!0,function(a){1===this.nodeType&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,!0,function(a){1===this.nodeType&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,this)});if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,
"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,this.nextSibling)});if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,e;null!=(e=this[d]);d++)if(!a||c.filter(a,[e]).length)!b&&1===e.nodeType&&(c.cleanData(e.getElementsByTagName("*")),c.cleanData([e])),e.parentNode&&e.parentNode.removeChild(e);return this},
empty:function(){for(var a=0,b;null!=(b=this[a]);a++)for(1===b.nodeType&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var a=this.outerHTML,b=this.ownerDocument;if(!a)a=b.createElement("div"),a.appendChild(this.cloneNode(!0)),a=a.innerHTML;return c.clean([a.replace(ca,"").replace(Ja,'="$1">').replace(M,"")],b)[0]}return this.cloneNode(!0)});!0===a&&(i(this,b),
i(this.find("*"),b.find("*")));return b},html:function(a){if(void 0===a)return this[0]&&1===this[0].nodeType?this[0].innerHTML.replace(ca,""):null;if("string"===typeof a&&!fa.test(a)&&(c.support.leadingWhitespace||!M.test(a))&&!A[(ea.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(da,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)if(1===this[b].nodeType)c.cleanData(this[b].getElementsByTagName("*")),this[b].innerHTML=a}catch(e){this.empty().append(a)}}else c.isFunction(a)?this.each(function(b){var d=
c(this);d.html(a.call(this,b,d.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),e=d.html();d.replaceWith(a.call(this,b,e))});"string"!==typeof a&&(a=c(a).detach());return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,
!0)},domManip:function(a,b,d){var e,f,h,m=a[0],k=[];if(!c.support.checkClone&&3===arguments.length&&"string"===typeof m&&ga.test(m))return this.each(function(){c(this).domManip(a,b,d,!0)});if(c.isFunction(m))return this.each(function(e){var f=c(this);a[0]=m.call(this,e,b?f.html():void 0);f.domManip(a,b,d)});if(this[0]){e=m&&m.parentNode;e=c.support.parentNode&&e&&11===e.nodeType&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,k);h=e.fragment;if(f=1===h.childNodes.length?h=h.firstChild:
h.firstChild){b=b&&c.nodeName(f,"tr");f=0;for(var g=this.length;f<g;f++)d.call(b?c.nodeName(this[f],"table")?this[f].getElementsByTagName("tbody")[0]||this[f].appendChild(this[f].ownerDocument.createElement("tbody")):this[f]:this[f],0<f||e.cacheable||1<this.length?h.cloneNode(!0):h)}k.length&&c.each(k,n)}return this}});c.buildFragment=function(a,b,d){var e,f,h,b=b&&b[0]?b[0].ownerDocument||b[0]:l;if(1===a.length&&"string"===typeof a[0]&&512>a[0].length&&b===l&&!fa.test(a[0])&&(c.support.checkClone||
!ga.test(a[0])))f=!0,(h=c.fragments[a[0]])&&1!==h&&(e=h);e||(e=b.createDocumentFragment(),c.clean(a,b,e,d));f&&(c.fragments[a[0]]=h?e:1);return{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var e=[],d=c(d),f=1===this.length&&this[0].parentNode;if(f&&11===f.nodeType&&1===f.childNodes.length&&1===d.length)return d[b](this[0]),this;for(var f=0,h=d.length;f<h;f++){var m=
(0<f?this.clone(!0):this).get();c(d[f])[b](m);e=e.concat(m)}return this.pushStack(e,a,d.selector)}});c.extend({clean:function(a,b,d,e){b=b||l;"undefined"===typeof b.createElement&&(b=b.ownerDocument||b[0]&&b[0].ownerDocument||l);for(var f=[],h=0,m;null!=(m=a[h]);h++)if("number"===typeof m&&(m+=""),m){if("string"===typeof m&&!Ia.test(m))m=b.createTextNode(m);else if("string"===typeof m){m=m.replace(da,"<$1></$2>");var k=(ea.exec(m)||["",""])[1].toLowerCase(),g=A[k]||A._default,t=g[0],i=b.createElement("div");
for(i.innerHTML=g[1]+m+g[2];t--;)i=i.lastChild;if(!c.support.tbody){t=Ha.test(m);k="table"===k&&!t?i.firstChild&&i.firstChild.childNodes:"<table>"===g[1]&&!t?i.childNodes:[];for(g=k.length-1;0<=g;--g)c.nodeName(k[g],"tbody")&&!k[g].childNodes.length&&k[g].parentNode.removeChild(k[g])}!c.support.leadingWhitespace&&M.test(m)&&i.insertBefore(b.createTextNode(M.exec(m)[0]),i.firstChild);m=i.childNodes}m.nodeType?f.push(m):f=c.merge(f,m)}if(d)for(h=0;f[h];h++)e&&c.nodeName(f[h],"script")&&(!f[h].type||
"text/javascript"===f[h].type.toLowerCase())?e.push(f[h].parentNode?f[h].parentNode.removeChild(f[h]):f[h]):(1===f[h].nodeType&&f.splice.apply(f,[h+1,0].concat(c.makeArray(f[h].getElementsByTagName("script")))),d.appendChild(f[h]));return f},cleanData:function(a){for(var b,d,e=c.cache,f=c.event.special,h=c.support.deleteExpando,m=0,k;null!=(k=a[m]);m++)if(!k.nodeName||!c.noData[k.nodeName.toLowerCase()])if(d=k[c.expando]){if((b=e[d])&&b.events)for(var g in b.events)f[g]?c.event.remove(k,g):c.removeEvent(k,
g,b.handle);h?delete k[c.expando]:k.removeAttribute&&k.removeAttribute(c.expando);delete e[d]}}});var ha=/alpha\([^)]*\)/i,Ka=/opacity=([^)]*)/,La=/-([a-z])/ig,Ma=/([A-Z])/g,ia=/^-?\d+(?:px)?$/i,Na=/^-?\d/,Oa={position:"absolute",visibility:"hidden",display:"block"},ra=["Left","Right"],sa=["Top","Bottom"],J,ja,N,Pa=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){return 2===arguments.length&&void 0===b?this:c.access(this,a,b,!0,function(a,b,f){return void 0!==f?c.style(a,b,f):c.css(a,
b)})};c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=J(a,"opacity","opacity");return""===c?"1":c}return a.style.opacity}}},cssNumber:{zIndex:!0,fontWeight:!0,opacity:!0,zoom:!0,lineHeight:!0},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(a&&!(3===a.nodeType||8===a.nodeType||!a.style)){var f,h=c.camelCase(b),g=a.style,k=c.cssHooks[h],b=c.cssProps[h]||h;if(void 0!==d){if(!("number"===typeof d&&isNaN(d)||null==d))if("number"===typeof d&&!c.cssNumber[h]&&
(d+="px"),!k||!("set"in k)||void 0!==(d=k.set(a,d)))try{g[b]=d}catch(l){}}else return k&&"get"in k&&void 0!==(f=k.get(a,!1,e))?f:g[b]}},css:function(a,b,d){var e,f=c.camelCase(b),h=c.cssHooks[f],b=c.cssProps[f]||f;if(h&&"get"in h&&void 0!==(e=h.get(a,!0,d)))return e;if(J)return J(a,b,f)},swap:function(a,b,c){var e={},f;for(f in b)e[f]=a.style[f],a.style[f]=b[f];c.call(a);for(f in b)a.style[f]=e[f]},camelCase:function(a){return a.replace(La,Pa)}});c.curCSS=c.css;c.each(["height","width"],function(a,
b){c.cssHooks[b]={get:function(a,e,f){var h;if(e){0!==a.offsetWidth?h=g(a,b,f):c.swap(a,Oa,function(){h=g(a,b,f)});if(0>=h&&(h=J(a,b,b),"0px"===h&&N&&(h=N(a,b,b)),null!=h))return""===h||"auto"===h?"0px":h;return 0>h||null==h?(h=a.style[b],""===h||"auto"===h?"0px":h):"string"===typeof h?h:h+"px"}},set:function(a,b){if(ia.test(b)){if(b=parseFloat(b),0<=b)return b+"px"}else return b}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return Ka.test((b&&a.currentStyle?a.currentStyle.filter:
a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){var d=a.style;d.zoom=1;var e=c.isNaN(b)?"":"alpha(opacity="+100*b+")",f=d.filter||"";d.filter=ha.test(f)?f.replace(ha,e):d.filter+" "+e}};l.defaultView&&l.defaultView.getComputedStyle&&(ja=function(a,b,d){var e,d=d.replace(Ma,"-$1").toLowerCase();if(b=a.ownerDocument.defaultView){if(b=b.getComputedStyle(a,null))e=b.getPropertyValue(d),""===e&&!c.contains(a.ownerDocument.documentElement,a)&&(e=c.style(a,d));return e}});l.documentElement.currentStyle&&
(N=function(a,b){var c,e,f=a.currentStyle&&a.currentStyle[b],h=a.style;if(!ia.test(f)&&Na.test(f))c=h.left,e=a.runtimeStyle.left,a.runtimeStyle.left=a.currentStyle.left,h.left="fontSize"===b?"1em":f||0,f=h.pixelLeft+"px",h.left=c,a.runtimeStyle.left=e;return""===f?"auto":f});J=ja||N;if(c.expr&&c.expr.filters)c.expr.filters.hidden=function(a){var b=a.offsetHeight;return 0===a.offsetWidth&&0===b||!c.support.reliableHiddenOffsets&&"none"===(a.style.display||c.css(a,"display"))},c.expr.filters.visible=
function(a){return!c.expr.filters.hidden(a)};var Qa=c.now(),Ra=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,Sa=/^(?:select|textarea)/i,Ta=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,Ua=/^(?:GET|HEAD|DELETE)$/,ta=/\[\]$/,D=/\=\?(&|$)/,S=/\?/,Va=/([?&])_=[^&]*/,Wa=/^(\w+:)?\/\/([^\/?#]+)/,Xa=/%20/g,Ya=/#.*$/,ka=c.fn.load;c.fn.extend({load:function(a,b,d){if("string"!==typeof a&&ka)return ka.apply(this,arguments);if(!this.length)return this;
var e=a.indexOf(" ");if(0<=e)var f=a.slice(e,a.length),a=a.slice(0,e);e="GET";b&&(c.isFunction(b)?(d=b,b=null):"object"===typeof b&&(b=c.param(b,c.ajaxSettings.traditional),e="POST"));var h=this;c.ajax({url:a,type:e,dataType:"html",data:b,complete:function(a,b){if("success"===b||"notmodified"===b)h.html(f?c("<div>").append(a.responseText.replace(Ra,"")).find(f):a.responseText);d&&h.each(d,[a.responseText,b,a])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?
c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||Sa.test(this.nodeName)||Ta.test(this.type))}).map(function(a,b){var d=c(this).val();return null==d?null:c.isArray(d)?c.map(d,function(a){return{name:b.name,value:a}}):{name:b.name,value:d}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(a){return this.bind(b,a)}});c.extend({get:function(a,b,d,e){c.isFunction(b)&&(e=e||d,d=
b,b=null);return c.ajax({type:"GET",url:a,data:b,success:d,dataType:e})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,e){c.isFunction(b)&&(e=e||d,d=b,b={});return c.ajax({type:"POST",url:a,data:b,success:d,dataType:e})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:!0,type:"GET",contentType:"application/x-www-form-urlencoded",processData:!0,async:!0,xhr:function(){return new window.XMLHttpRequest},
accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},ajax:function(a){var b=c.extend(!0,{},c.ajaxSettings,a),d,e,f,h=b.type.toUpperCase(),g=Ua.test(h);b.url=b.url.replace(Ya,"");b.context=a&&null!=a.context?a.context:b;if(b.data&&b.processData&&"string"!==typeof b.data)b.data=c.param(b.data,b.traditional);if("jsonp"===b.dataType){if("GET"===h)D.test(b.url)||(b.url+=(S.test(b.url)?
"&":"?")+(b.jsonp||"callback")+"=?");else if(!b.data||!D.test(b.data))b.data=(b.data?b.data+"&":"")+(b.jsonp||"callback")+"=?";b.dataType="json"}if("json"===b.dataType&&(b.data&&D.test(b.data)||D.test(b.url))){d=b.jsonpCallback||"jsonp"+Qa++;if(b.data)b.data=(b.data+"").replace(D,"="+d+"$1");b.url=b.url.replace(D,"="+d+"$1");b.dataType="script";var k=window[d];window[d]=function(a){if(c.isFunction(k))k(a);else{window[d]=void 0;try{delete window[d]}catch(h){}}f=a;c.handleSuccess(b,j,e,f);c.handleComplete(b,
j,e,f);n&&n.removeChild(o)}}if("script"===b.dataType&&null===b.cache)b.cache=!1;if(!1===b.cache&&g){var i=c.now(),t=b.url.replace(Va,"$1_="+i);b.url=t+(t===b.url?(S.test(b.url)?"&":"?")+"_="+i:"")}b.data&&g&&(b.url+=(S.test(b.url)?"&":"?")+b.data);b.global&&0===c.active++&&c.event.trigger("ajaxStart");i=(i=Wa.exec(b.url))&&(i[1]&&i[1].toLowerCase()!==location.protocol||i[2].toLowerCase()!==location.host);if("script"===b.dataType&&"GET"===h&&i){var n=l.getElementsByTagName("head")[0]||l.documentElement,
o=l.createElement("script");if(b.scriptCharset)o.charset=b.scriptCharset;o.src=b.url;if(!d){var q=!1;o.onload=o.onreadystatechange=function(){if(!q&&(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState))q=!0,c.handleSuccess(b,j,e,f),c.handleComplete(b,j,e,f),o.onload=o.onreadystatechange=null,n&&o.parentNode&&n.removeChild(o)}}n.insertBefore(o,n.firstChild)}else{var p=!1,j=b.xhr();if(j){b.username?j.open(h,b.url,b.async,b.username,b.password):j.open(h,b.url,b.async);try{(null!=
b.data&&!g||a&&a.contentType)&&j.setRequestHeader("Content-Type",b.contentType),b.ifModified&&(c.lastModified[b.url]&&j.setRequestHeader("If-Modified-Since",c.lastModified[b.url]),c.etag[b.url]&&j.setRequestHeader("If-None-Match",c.etag[b.url])),i||j.setRequestHeader("X-Requested-With","XMLHttpRequest"),j.setRequestHeader("Accept",b.dataType&&b.accepts[b.dataType]?b.accepts[b.dataType]+", */*; q=0.01":b.accepts._default)}catch(r){}if(b.beforeSend&&!1===b.beforeSend.call(b.context,j,b))return b.global&&
1===c.active--&&c.event.trigger("ajaxStop"),j.abort(),!1;b.global&&c.triggerGlobal(b,"ajaxSend",[j,b]);var s=j.onreadystatechange=function(a){if(!j||0===j.readyState||"abort"===a){if(p||c.handleComplete(b,j,e,f),p=!0,j)j.onreadystatechange=c.noop}else if(!p&&j&&(4===j.readyState||"timeout"===a)){p=!0;j.onreadystatechange=c.noop;e="timeout"===a?"timeout":!c.httpSuccess(j)?"error":b.ifModified&&c.httpNotModified(j,b.url)?"notmodified":"success";var h;if("success"===e)try{f=c.httpData(j,b.dataType,b)}catch(k){e=
"parsererror",h=k}"success"===e||"notmodified"===e?d||c.handleSuccess(b,j,e,f):c.handleError(b,j,e,h);d||c.handleComplete(b,j,e,f);"timeout"===a&&j.abort();b.async&&(j=null)}};try{var u=j.abort;j.abort=function(){j&&Function.prototype.call.call(u,j);s("abort")}}catch(C){}b.async&&0<b.timeout&&setTimeout(function(){j&&!p&&s("timeout")},b.timeout);try{j.send(g||null==b.data?null:b.data)}catch(y){c.handleError(b,j,null,y),c.handleComplete(b,j,e,f)}b.async||s();return j}}},param:function(a,b){var d=[],
e=function(a,b){b=c.isFunction(b)?b():b;d[d.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};if(void 0===b)b=c.ajaxSettings.traditional;if(c.isArray(a)||a.jquery)c.each(a,function(){e(this.name,this.value)});else for(var f in a)B(f,a[f],b,e);return d.join("&").replace(Xa,"+")}});c.extend({active:0,lastModified:{},etag:{},handleError:function(a,b,d,e){a.error&&a.error.call(a.context,b,d,e);a.global&&c.triggerGlobal(a,"ajaxError",[b,a,e])},handleSuccess:function(a,b,d,e){a.success&&a.success.call(a.context,
e,d,b);a.global&&c.triggerGlobal(a,"ajaxSuccess",[b,a])},handleComplete:function(a,b,d){a.complete&&a.complete.call(a.context,b,d);a.global&&c.triggerGlobal(a,"ajaxComplete",[b,a]);a.global&&1===c.active--&&c.event.trigger("ajaxStop")},triggerGlobal:function(a,b,d){(a.context&&null==a.context.url?c(a.context):c.event).trigger(b,d)},httpSuccess:function(a){try{return!a.status&&"file:"===location.protocol||200<=a.status&&300>a.status||304===a.status||1223===a.status}catch(b){}return!1},httpNotModified:function(a,
b){var d=a.getResponseHeader("Last-Modified"),e=a.getResponseHeader("Etag");d&&(c.lastModified[b]=d);e&&(c.etag[b]=e);return 304===a.status},httpData:function(a,b,d){var e=a.getResponseHeader("content-type")||"",f="xml"===b||!b&&0<=e.indexOf("xml"),a=f?a.responseXML:a.responseText;f&&"parsererror"===a.documentElement.nodeName&&c.error("parsererror");d&&d.dataFilter&&(a=d.dataFilter(a,b));"string"===typeof a&&("json"===b||!b&&0<=e.indexOf("json")?a=c.parseJSON(a):("script"===b||!b&&0<=e.indexOf("javascript"))&&
c.globalEval(a));return a}});if(window.ActiveXObject)c.ajaxSettings.xhr=function(){if("file:"!==window.location.protocol)try{return new window.XMLHttpRequest}catch(a){}try{return new window.ActiveXObject("Microsoft.XMLHTTP")}catch(b){}};c.support.ajax=!!c.ajaxSettings.xhr();var P={},Za=/^(?:toggle|show|hide)$/,$a=/^([+\-]=)?([\d+.\-]+)(.*)$/,O,T=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,
b,d){if(a||0===a)return this.animate(y("show",3),a,b,d);for(var d=0,e=this.length;d<e;d++){a=this[d];b=a.style.display;if(!c.data(a,"olddisplay")&&"none"===b)b=a.style.display="";""===b&&"none"===c.css(a,"display")&&c.data(a,"olddisplay",t(a.nodeName))}for(d=0;d<e;d++)if(a=this[d],b=a.style.display,""===b||"none"===b)a.style.display=c.data(a,"olddisplay")||"";return this},hide:function(a,b,d){if(a||0===a)return this.animate(y("hide",3),a,b,d);a=0;for(b=this.length;a<b;a++)d=c.css(this[a],"display"),
"none"!==d&&c.data(this[a],"olddisplay",d);for(a=0;a<b;a++)this[a].style.display="none";return this},_toggle:c.fn.toggle,toggle:function(a,b,d){var e="boolean"===typeof a;c.isFunction(a)&&c.isFunction(b)?this._toggle.apply(this,arguments):null==a||e?this.each(function(){var b=e?a:c(this).is(":hidden");c(this)[b?"show":"hide"]()}):this.animate(y("toggle",3),a,b,d);return this},fadeTo:function(a,b,c,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,
b,d,e){var f=c.speed(b,d,e);return c.isEmptyObject(a)?this.each(f.complete):this[!1===f.queue?"each":"queue"](function(){var b=c.extend({},f),d,e=1===this.nodeType,g=e&&c(this).is(":hidden"),i=this;for(d in a){var l=c.camelCase(d);d!==l&&(a[l]=a[d],delete a[d],d=l);if("hide"===a[d]&&g||"show"===a[d]&&!g)return b.complete.call(this);if(e&&("height"===d||"width"===d))if(b.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY],"inline"===c.css(this,"display")&&"none"===c.css(this,"float"))c.support.inlineBlockNeedsLayout?
"inline"===t(this.nodeName)?this.style.display="inline-block":(this.style.display="inline",this.style.zoom=1):this.style.display="inline-block";if(c.isArray(a[d]))(b.specialEasing=b.specialEasing||{})[d]=a[d][1],a[d]=a[d][0]}if(null!=b.overflow)this.style.overflow="hidden";b.curAnim=c.extend({},a);c.each(a,function(d,e){var f=new c.fx(i,b,d);if(Za.test(e))f["toggle"===e?g?"show":"hide":e](a);else{var k=$a.exec(e),m=f.cur()||0;if(k){var l=parseFloat(k[2]),t=k[3]||"px";"px"!==t&&(c.style(i,d,(l||1)+
t),m*=(l||1)/f.cur(),c.style(i,d,m+t));k[1]&&(l=("-="===k[1]?-1:1)*l+m);f.custom(m,l,t)}else f.custom(m,e,"")}});return!0})},stop:function(a,b){var d=c.timers;a&&this.queue([]);this.each(function(){for(var a=d.length-1;0<=a;a--)if(d[a].elem===this){if(b)d[a](!0);d.splice(a,1)}});b||this.dequeue();return this}});c.each({slideDown:y("show",1),slideUp:y("hide",1),slideToggle:y("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(a,
c,f){return this.animate(b,a,c,f)}});c.extend({speed:function(a,b,d){var e=a&&"object"===typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;e.old=e.complete;e.complete=function(){!1!==e.queue&&c(this).dequeue();c.isFunction(e.old)&&e.old.call(this)};return e},easing:{linear:function(a,b,c,e){return c+e*a},swing:function(a,
b,c,e){return(-Math.cos(a*Math.PI)/2+0.5)*e+c}},timers:[],fx:function(a,b,c){this.options=b;this.elem=a;this.prop=c;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(null!=this.elem[this.prop]&&(!this.elem.style||null==this.elem.style[this.prop]))return this.elem[this.prop];var a=parseFloat(c.css(this.elem,this.prop));return a&&-1E4<a?a:0},custom:function(a,
b,d){function e(a){return f.step(a)}var f=this,h=c.fx;this.startTime=c.now();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=this.state=0;e.elem=this.elem;e()&&c.timers.push(e)&&!O&&(O=setInterval(h.tick,h.interval))},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=!0;this.custom("width"===this.prop||"height"===this.prop?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,
this.prop);this.options.hide=!0;this.custom(this.cur(),0)},step:function(a){var b=c.now(),d=!0;if(a||b>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=!0;for(var e in this.options.curAnim)!0!==this.options.curAnim[e]&&(d=!1);if(d){if(null!=this.options.overflow&&!c.support.shrinkWrapBlocks){var f=this.elem,h=this.options;c.each(["","X","Y"],function(a,b){f.style["overflow"+b]=h.overflow[a]})}this.options.hide&&c(this.elem).hide();
if(this.options.hide||this.options.show)for(var g in this.options.curAnim)c.style(this.elem,g,this.options.orig[g]);this.options.complete.call(this.elem)}return!1}a=b-this.startTime;this.state=a/this.options.duration;b=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||b](this.state,a,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update();return!0}};c.extend(c.fx,{tick:function(){for(var a=
c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},interval:13,stop:function(){clearInterval(O);O=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){a.elem.style&&null!=a.elem.style[a.prop]?a.elem.style[a.prop]=("width"===a.prop||"height"===a.prop?Math.max(0,a.now):a.now)+a.unit:a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===
b.elem}).length};var ab=/^t(?:able|d|h)$/i,la=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in l.documentElement?function(a){var b=this[0],d;if(a)return this.each(function(b){c.offset.setOffset(this,a,b)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{d=b.getBoundingClientRect()}catch(e){}var f=b.ownerDocument,h=f.documentElement;if(!d||!c.contains(h,b))return d||{top:0,left:0};b=f.body;f=C(f);return{top:d.top+(f.pageYOffset||c.support.boxModel&&
h.scrollTop||b.scrollTop)-(h.clientTop||b.clientTop||0),left:d.left+(f.pageXOffset||c.support.boxModel&&h.scrollLeft||b.scrollLeft)-(h.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(b){c.offset.setOffset(this,a,b)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d,e=b.offsetParent,f=b.ownerDocument,h=f.documentElement,g=f.body;d=(f=f.defaultView)?f.getComputedStyle(b,null):b.currentStyle;
for(var k=b.offsetTop,l=b.offsetLeft;(b=b.parentNode)&&b!==g&&b!==h&&!(c.offset.supportsFixedPosition&&"fixed"===d.position);){d=f?f.getComputedStyle(b,null):b.currentStyle;k-=b.scrollTop;l-=b.scrollLeft;if(b===e){k+=b.offsetTop;l+=b.offsetLeft;if(c.offset.doesNotAddBorder&&(!c.offset.doesAddBorderForTableAndCells||!ab.test(b.nodeName)))k+=parseFloat(d.borderTopWidth)||0,l+=parseFloat(d.borderLeftWidth)||0;e=b.offsetParent}c.offset.subtractsBorderForOverflowNotVisible&&"visible"!==d.overflow&&(k+=
parseFloat(d.borderTopWidth)||0,l+=parseFloat(d.borderLeftWidth)||0)}if("relative"===d.position||"static"===d.position)k+=g.offsetTop,l+=g.offsetLeft;c.offset.supportsFixedPosition&&"fixed"===d.position&&(k+=Math.max(h.scrollTop,g.scrollTop),l+=Math.max(h.scrollLeft,g.scrollLeft));return{top:k,left:l}};c.offset={initialize:function(){var a=l.body,b=l.createElement("div"),d,e,f,h=parseFloat(c.css(a,"marginTop"))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",
visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";a.insertBefore(b,a.firstChild);d=b.firstChild;e=d.firstChild;f=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=5!==e.offsetTop;this.doesAddBorderForTableAndCells=5===
f.offsetTop;e.style.position="fixed";e.style.top="20px";this.supportsFixedPosition=20===e.offsetTop||15===e.offsetTop;e.style.position=e.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=-5===e.offsetTop;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==h;a.removeChild(b);c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();c.offset.doesNotIncludeMarginInBodyOffset&&(b+=parseFloat(c.css(a,
"marginTop"))||0,d+=parseFloat(c.css(a,"marginLeft"))||0);return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if("static"===e)a.style.position="relative";var f=c(a),h=f.offset(),g=c.css(a,"top"),k=c.css(a,"left"),l="absolute"===e&&-1<c.inArray("auto",[g,k]),e={},i={};l&&(i=f.position());g=l?i.top:parseInt(g,10)||0;k=l?i.left:parseInt(k,10)||0;c.isFunction(b)&&(b=b.call(a,d,h));if(null!=b.top)e.top=b.top-h.top+g;if(null!=b.left)e.left=b.left-h.left+k;"using"in b?b.using.call(a,
e):f.css(e)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=la.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||l.body;a&&!la.test(a.nodeName)&&
"static"===c.css(a,"position");)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(b){var f=this[0],h;if(!f)return null;return void 0!==b?this.each(function(){(h=C(this))?h.scrollTo(!a?b:c(h).scrollLeft(),a?b:c(h).scrollTop()):this[d]=b}):(h=C(f))?"pageXOffset"in h?h[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&h.document.documentElement[d]||h.document.body[d]:f[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+
b]=function(){return this[0]?parseFloat(c.css(this[0],d,"padding")):null};c.fn["outer"+b]=function(a){return this[0]?parseFloat(c.css(this[0],d,a?"margin":"border")):null};c.fn[d]=function(a){var f=this[0];if(!f)return null==a?null:this;if(c.isFunction(a))return this.each(function(b){var f=c(this);f[d](a.call(this,b,f[d]()))});if(c.isWindow(f))return"CSS1Compat"===f.document.compatMode&&f.document.documentElement["client"+b]||f.document.body["client"+b];if(9===f.nodeType)return Math.max(f.documentElement["client"+
b],f.body["scroll"+b],f.documentElement["scroll"+b],f.body["offset"+b],f.documentElement["offset"+b]);if(void 0===a){var f=c.css(f,d),h=parseFloat(f);return c.isNaN(h)?f:h}return this.css(d,"string"===typeof a?a:a+"px")}});window.jQuery=c;window.$=$;var ma=!1;$(window).load(function(){ma=!0});$.fn.windowLoaded=function(a){ma?a.call(this):this.load(a)};c.fn.doOnce=function(a,b){var c=this;c.length&&(b?G.req(b,function(){a.apply(c,arguments)}):a.apply(c));return this};return c});
G.def("GUtils",["jQuery"],function(j){var r=Array.prototype,q=Object.prototype,o=String.prototype,p=Array.isArray,s=r.filter,u=r.every,i=r.some,n=r.map,g=q.toString,B=/^[^<]*(<[\w\W]+>)[^>]*$/,y={"[object Boolean]":"boolean","[object Number]":"number","[object String]":"string","[object Function]":"function","[object Array]":"array","[object Date]":"date","[object RegExp]":"regexp","[object Object]":"object"};G.format=function(g,i,l){if(!i)return g;var c;return"object"!==typeof i?(c=l||i,g.replace(RegExp(l?
i:"{v}","g"),""+c)):g.replace(l||/\{([^{}]+)\}/g,function(g,l){c=i[l];return void 0!==c?""+c:""})};G.ellipsis=function(g,i){return g.length>i?g.slice(0,i)+"...":g};G.type=function(i){return null==i?""+i:y[g.call(i)]||"object"};G.ua=function(){var g=parseInt(j.browser.version,10),i=j.browser.msie&&9>g,l=navigator.userAgent;return{isIE:i,isIE6:i&&6===g,isIE8:i&&8===g,isIE7:i&&7===g,isIE9:j.browser.msie&&9===g,isOpera:j.browser.opera,isIpad:null!==l.match(/iPad/i),isIphone:null!==l.match(/iPhone/i)}}();
G.isFun=function(g){return"function"===G.type(g)};G.isArray=p||function(g){return"array"===G.type(g)};G.isNumber=function(g){return"number"===G.type(g)};G.isHtml=function(g){return B.test(g)};G.each=function(g,i,l){if(null!=g)if(r.forEach&&g.forEach===r.forEach)g.forEach(i,l);else if(G.isNumber(g.length))for(var c=0,n=g.length;c<n;c++)c in g&&i.call(l,g[c],c,g);else for(c in g)q.hasOwnProperty.call(g,c)&&i.call(l,g[c],c,g)};G.filter=function(g,i,l){var c=[];if(null!=g){if(s&&g.filter===s)return g.filter(i,
l);G.each(g,function(g,n,j){i.call(l,g,n,j)&&c.push(g)});return c}};G.every=function(g,i,l){if(null==g)return!0;if(u&&g.every===u)return g.every(i,l);for(var c=0,n=g.length;c<n;c++)if(!i.call(l,g[c],c,g))return!1;return!0};G.some=function(g,n,l){if(null==g)return!1;if(i&&g.some===i)return g.some(n,l);for(var c=0,j=g.length;c<j;c++)if(n.call(l,g[c],c,g))return!0;return!1};G.map=function(g,i,l){var c=[];if(null!=g){if(n&&g.map===n)return g.map(i,l);G.each(g,function(g,n,j){c.push(i.call(l,g,n,j))});
return c}};G.unique=function(g){if(null!=g){g.sort();for(var i=1;i<g.length;i++)g[i-1]===g[i]&&g.splice(i--,1);return g}};if(!o.trim)o.trim=function(){var g=/^\s+/,i=/\s+$/;return function(){return this.replace(g,"").replace(i,"")}}();if(!Object.create)Object.create=function(g){function i(){}if(1<arguments.length)throw Error("Object.create implementation only accepts the first parameter.");i.prototype=g;return new i};if(!r.indexOf)r.indexOf=function(g,i){if(void 0===this||null===this)throw new TypeError;
var l=Object(this),c=l.length>>>0;if(0===c)return-1;var n=0;0<arguments.length&&(n=Number(arguments[1]),isNaN(n)?n=0:0!==n&&n!==1/0&&n!==-(1/0)&&(n=(0<n||-1)*Math.floor(Math.abs(n))));if(n>=c)return-1;for(n=0<=n?n:Math.max(c-Math.abs(n),0);n<c;n++)if(n in l&&l[n]===g)return n;return-1};return G});
G.def("cookies",{get:function(j){if(0<document.cookie.length){var r=document.cookie.indexOf(j+"=");if(-1!=r){r=r+j.length+1;j=document.cookie.indexOf(";",r);if(-1==j)j=document.cookie.length;return unescape(document.cookie.substring(r,j))}}return""},set:function(j,r,q,o){document.cookie=j+"="+escape(r)+(null==q?"":";expires="+q.toGMTString())+";path="+(o||"/");return this},remove:function(j,r){var q=new Date;q.setTime(q.getTime()-1);var o=this.get(j);if(null!=o)document.cookie=j+"="+o+";expires="+
q.toGMTString()+";path="+(r||"/")}});G.def("api",["jQuery","cookies"],function(j,r){j.ajaxSettings.traditional=!0;var q=r.get("_32353_access_token");j.ajax=function(j,p){return function(){return j.apply(this,p.apply(this,arguments)||arguments)}}(j.ajax,function(j){var p=j.data;if(q)p=p||{},p.access_token=q;j.data=p});return{checkToken:function(){q=r.get("_32353_access_token")},getToken:function(){return q}}});
G.def("placeholder",function(){function j(j,o){""===j.val()&&j.val(o).css("color","#CCC")}var r=""===document.createElement("textarea").placeholder;return{init:function(q){if(!r){var o=$(q),p=o.attr("placeholder"),s=o.css("color");j(o,p);o.focus(function(){o.val()===p&&o.val("").css("color",s)}).blur(function(){j(o,p)})}return this},submit:function(j,o,p){var s=$(j),j=$(o);r?j.submit(p):j.submit(function(){var j=s.attr("placeholder");s.val()===j&&s.val("");return p.apply(this,arguments)});return this},
support:r}});G.def("gPopMenu",function(){function j(j,q){var o=q?j:j.children(":eq(0)"),p=q?j.next():j.children(":eq(1)");o.mouseover(function(){q?(G.ua.isIE6&&p.width(o.outerWidth()+2),p.show()):j.addClass("hover")});q?p.mouseleave(function(){p.hide()}):j.mouseleave(function(){j.removeClass("hover")})}return function(r,q){$(r).each(function(){j($(this),q)})}});
G.def("missionLoader",function(){function j(j,s,r){for(var i,n,g=function(g){return function(i){i(g,r,s)}},B=0,y=j.length;B<y;B++)i=j[B],r[i]&&-1===r[i].step||(null==r[i]&&(r[i]={step:0}),n=q[i],(!n||n(s,r))&&G.req("missions/"+o[i],g(i)))}var r={all:["gGuideNavFocus"],askLogin:["askGuideLogin"],askContent:["askGuideContent","askGuideContent2"],tagIndexPage:["tagGuideLogin"],indexLogin:["indexGuideActive"]},q={},o={askGuideLogin:"guide",askGuideContent:"guide",askGuideContent2:"guide",gGuideNavFocus:"guide",
tagGuideLogin:"guide",indexGuideActive:"guide"};return function(){if("undefined"!==typeof g_mission_status&&ukey){"undefined"===typeof g_page_name&&(g_page_name="");var o=g_page_name,q=r[o],u=g_mission_status,i=r.all;q&&j(q,o,u);i&&j(i,"all",u)}}});
G.def("JSON2",function(){function j(g){return 10>g?"0"+g:g}function r(g){p.lastIndex=0;return p.test(g)?'"'+g.replace(p,function(g){var n=i[g];return"string"===typeof n?n:"\\u"+("0000"+g.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+g+'"'}function q(g,i){var j,o,p,l,c=s,z,x=i[g];x&&"object"===typeof x&&"function"===typeof x.toJSON&&(x=x.toJSON(g));"function"===typeof n&&(x=n.call(i,g,x));switch(typeof x){case "string":return r(x);case "number":return isFinite(x)?""+x:"null";case "boolean":case "null":return""+
x;case "object":if(!x)return"null";s+=u;z=[];if("[object Array]"===Object.prototype.toString.apply(x)){l=x.length;for(j=0;j<l;j+=1)z[j]=q(j,x)||"null";p=0===z.length?"[]":s?"[\n"+s+z.join(",\n"+s)+"\n"+c+"]":"["+z.join(",")+"]";s=c;return p}if(n&&"object"===typeof n){l=n.length;for(j=0;j<l;j+=1)"string"===typeof n[j]&&(o=n[j],(p=q(o,x))&&z.push(r(o)+(s?": ":":")+p))}else for(o in x)Object.prototype.hasOwnProperty.call(x,o)&&(p=q(o,x))&&z.push(r(o)+(s?": ":":")+p);p=0===z.length?"{}":s?"{\n"+s+z.join(",\n"+
s)+"\n"+c+"}":"{"+z.join(",")+"}";s=c;return p}}if(!window.JSON)window.JSON={};if("function"!==typeof Date.prototype.toJSON)Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+j(this.getUTCMonth()+1)+"-"+j(this.getUTCDate())+"T"+j(this.getUTCHours())+":"+j(this.getUTCMinutes())+":"+j(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var o=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
p=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,s,u,i={"":"\\b","\t":"\\t","\n":"\\n","":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},n;if("function"!==typeof JSON.stringify)JSON.stringify=function(g,i,j){var o;u=s="";if("number"===typeof j)for(o=0;o<j;o+=1)u+=" ";else"string"===typeof j&&(u=j);if((n=i)&&"function"!==typeof i&&("object"!==typeof i||"number"!==typeof i.length))throw Error("JSON.stringify");return q("",{"":g})};
if("function"!==typeof JSON.parse)JSON.parse=function(g,i){function j(g,l){var c,n,o=g[l];if(o&&"object"===typeof o)for(c in o)Object.prototype.hasOwnProperty.call(o,c)&&(n=j(o,c),void 0!==n?o[c]=n:delete o[c]);return i.call(g,l,o)}var n,g=""+g;o.lastIndex=0;o.test(g)&&(g=g.replace(o,function(g){return"\\u"+("0000"+g.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(g.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return n=eval("("+g+")"),"function"===typeof i?j({"":n},""):n;throw new SyntaxError("JSON.parse");}}());
G.def("store",["JSON2"],function(){var j={set:function(){},get:function(){},remove:function(){},clear:function(){},isSupport:!1};if("localStorage"in window){var r=window.localStorage,q=function(j,p){var q=r[j];return function(u){setTimeout(function(){u=u||window.storageEvent;var i=u.key,n=u.newValue;if(!i){var g=r[j];g!=q&&(i=j,n=g)}i==j&&(p&&p(null==n?null:JSON.parse(n)),q=n)},0)}};j.set=function(j,p){r.setItem(j,JSON.stringify(p))};j.get=function(j){j=r.getItem(j);return null==j?null:JSON.parse(j)};
j.remove=function(j){r.removeItem(j)};j.clear=function(){r.clear()};j.onStorage=function(j,p){window.addEventListener?window.addEventListener("storage",q(j,p),!1):document.attachEvent("storage",q(j,p))};j.isSupport=!0}return j});G.def("Base",function(){var j=function(){};j.extend=function(j,q){var o=q||this,p;for(p in o)o.hasOwnProperty(p)&&"prototype"!==p&&(j[p]=o[p]);for(var s in o.prototype)o.prototype.hasOwnProperty(s)&&(j.prototype[s]=o.prototype[s])};return j});
G.def("Event",["Base"],function(j){function r(){}var q=Array.prototype.slice;r.prototype.on=function(j,p,q,r){this.eventQueue=this.eventQueue||{};this.eventQueue[j]=this.eventQueue[j]||[];this.eventQueue[j].push({callback:p,context:q,once:r});return this};r.prototype.off=function(j,p){this.eventQueue=this.eventQueue||{};if(null!=this.eventQueue[j])return p?(this.eventQueue[j]=G.filter(this.eventQueue[j],function(j){return j.callback!==p}),0===this.eventQueue[j].length&&delete this.eventQueue[j]):
delete this.eventQueue[j],this};r.prototype.fire=function(j,p){this.eventQueue=this.eventQueue||{};var r=this.eventQueue[j],u=!0;if(r){var i=q.call(arguments,1);G.each(r,function(n){!1===n.callback.apply(n.context,i)&&(u=!1);n.once&&this.off(j,n.callback)},this)}return u};j.extend(r);return r});
G.def("OneTask",["store","JSON2","cookies","Event"],function(j,r,q,o){function p(g,j,i){function n(){o._run()}this.name="T"+g;this.serverTimeKey=this.name+"T";this.jobMsgKey=this.name+"M";this.asyncJob=j;this.jobMsg=null;this.isServer=!1;this.params=i&&i.params;this.serverTimeout=i&&i.serverTimeout||2E3;this.intervalTime=i&&i.interval||3E4;this.serverCheckInterval=this.jobRunInterval=this.timeUpdateInterval=0;this.inited=this.isRunning=!1;var o=this;o.callback=function(g,c){o.fire("callback",c?g:
JSON.parse(g));o.jobRunInterval=setTimeout(n,o.intervalTime)}}var s=location.pathname+"?"+(new Date).getTime()+Math.random(),u=j.isSupport?j.set:function(g,i){q.set(g,JSON.stringify(i))},i=j.isSupport?j.get:function(g){return(g=q.get(g))?JSON.parse(g):null},n=j.isSupport?j.remove:function(g){q.remove(g)};o.extend(p);p.prototype._run=function(){var g=this;if(!g.isRunning)return this;if(g.isServer){var i=function(i){if(g.isServer){var j=JSON.stringify(i);u(g.jobMsgKey,j);if(g.jobMsg!==j)g.fire("changeCallBack",
i),g.jobMsg=j;g.callback(i,!0)}else g.callback(g.jobMsg)};this.params?g.asyncJob.apply(g,[i].concat(this.params)):g.asyncJob.call(g,i)}else g.callback(g.jobMsg);return this};p.prototype.start=function(){var g=this;if(g.isRunning)return this;g.isRunning=!0;g.switchToServer();if(j.isSupport&&!g.inited)j.onStorage(g.jobMsgKey,function(i){if(g.isRunning&&g.jobMsg!==i)g.jobMsg=i,g.fire("changeCallBack",JSON.parse(i))});g.serverCheckInterval=setInterval(function(){g.check();if(!g.isServer){var n=parseInt(i(g.serverTimeKey),
10)||0,o=(new Date).getTime();(!n||o-n>g.serverTimeout)&&g.switchToServer();if(!j.isSupport&&g.isRunning&&(n=i(g.jobMsgKey),g.jobMsg!==n))g.jobMsg=n,g.fire("changeCallBack",JSON.parse(n))}},this.serverTimeout/2);g._run();g.inited=!0;return this};p.prototype.stop=function(){this.isRunning=!1;this.switchToClient();clearInterval(this.serverCheckInterval);return this};p.prototype.cancel=function(){this.isServer&&(n(this.name),n(this.serverTimeKey),n(this.jobMsgKey));clearInterval(this.timeUpdateInterval);
clearTimeout(this.jobRunInterval);clearInterval(this.serverCheckInterval);return this};p.prototype.check=function(g){(g=g||i(this.name))?this.isServer=g!==s?!1:!0:this.switchToServer();return this};p.prototype.switchToServer=function(){var g=this;if(g.isServer)return this;g.isServer=!0;u(g.name,s);u(g.serverTimeKey,(new Date).getTime());g.timeUpdateInterval=setInterval(function(){i(g.name)!==s?clearInterval(g.timeUpdateInterval):u(g.serverTimeKey,(new Date).getTime())},g.serverTimeout/2);return this};
p.prototype.switchToClient=function(){if(!this.isServer)return this;this.isServer=!1;n(this.name);n(this.serverTimeKey);clearInterval(this.timeUpdateInterval);return this};p.prototype.useCookie=!j.isSupport;p.prototype.onChangeCallBack=function(g){this.on("changeCallBack",g,this);return this};p.prototype.onCallBack=function(g){this.on("callback",g,this);return this};return p});
G.def("NotifyUtil",["OneTask","Event","JSON2"],function(j,r){function q(){this.on("update",function(i,g){o=null==g?o:g;p=null==i?p:i})}var o=-1,p=-1,s={getNotifyInfo:function(i){$.ajax({url:"/apis/community/rn_num.json",type:"get",dataType:"json",success:i,cache:!1})},getNotifyList:function(i){$.ajax({url:"/apis/community/notice.json",type:"get",dataType:"json",success:i,cache:!1})},getRemindList:function(i){$.ajax({url:"/apis/community/reminder.json",type:"get",dataType:"json",success:i,cache:!1})},
deleteNotify:function(i,g,j,o){$.ajax({url:"/apis/community/notice_ignore.json",data:{nid:i},type:"put",dataType:"json",success:j,error:o})}};q.prototype={deleteNotify:function(i,g,j){var o=this;s.deleteNotify(i,"",function(i){i=i.result;o.fire("update",null,i.count,i.list,null,i.all);g&&g()},j)},deleteAllNotify:function(i,g){s.deleteNotify("","all",function(){o=p=0;i&&i()},g)},getNotifyList:function(i,g){s.getNotifyList(i,g)},getRemindList:function(i,g){s.getRemindList(i,g)},onUpdate:function(i){this.on("update",
i)},onUpdateRemind:function(i){this.on("updateRemind",i)}};r.extend(q);var u=new q,i=new j("N",function(i){s.getNotifyInfo(function(g){i(g.result)})},{interval:3E4});i.onChangeCallBack(function(i){if(null!=i&&(i.n!==o||i.r!==p))i.n?u.getNotifyList(function(g){u.fire("update",i.r,i.n,g.result)}):u.fire("update",i.r,i.n),i.r&&u.getRemindList(function(g){u.fire("updateRemind",g.result)})}).start();i.useCookie&&$(window).unload(function(){i.cancel()});return u});
G.def("tmpl",function(){var j={};return function q(o,p){var s=!/\W/.test(o)?j[o]=j[o]||q(document.getElementById(o).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+o.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');");return p?s(p):s}});
G.def("notify",["cookies","NotifyUtil","tmpl"],function(j,r,q){function o(){function j(n){-1===$.inArray(n,i.dismissIds)&&(i.dismissIds.push(n),1===i.dismissIds.length&&r.deleteNotify(i.dismissIds[0],function(){i.$noticeBlock.find("li[data-id="+i.dismissIds[0]+"]");i.$noticeNum.text(i.noticeNum);i.noticeNum?i.$noticeDiv.addClass(s):i.$noticeDiv.removeClass(s);i.dismissIds.shift();i.dismissIds.length&&j(i.dismissIds[0]);0===i.noticeNum&&(i.$noticeDiv.removeClass(s),i.hide())},function(){setTimeout(function(){j(i.dismissIds[0])},
3E4)}))}var i=this;this.remindList=[];this.remindNum=0;this.$remindDiv=$("#gheaderRemind");this.$remindBlock=$("#remindBlock");this.$remindNum=$("#msgNum");this.msgNum=0;this.$msgNum=$("#msgNum");this.draftNum=0;this.$draftNum=$("#draftNum");this.$remindTitle=this.$remindDiv.children().eq(0);this.noticeList=[];this.noticeNum=0;this.$noticeDiv=$("#gheaderNotice");this.$noticeBlock=$("#noticeBlock");this.$noticeNum=$("#noticeNum");this.$noticeTitle=this.$noticeDiv.children().eq(0);this.$settingsDiv=
$("#gheaderSettings");this.$settingsBlock=$("#settingsBlock");this.$settingsTitle=this.$settingsDiv.children().eq(0);this.dismissIds=[];this.$noticeDiv.length&&this.$noticeBlock.length&&(this.$noticeBlock.delegate("[data-operation=openLink]","click",function(){var n=$(this).parents("li"),g=n.data("id");n.siblings().length?(i.noticeNum--,i.$noticeNum.text(i.noticeNum),i.noticeNum?i.$noticeDiv.addClass(s):i.$noticeDiv.removeClass(s),n.fadeOut("slow",function(){n.remove()})):(i.$noticeTitle.html("通知"),
i.$noticeDiv.removeClass(s),i.$noticeBlock.fadeOut("slow",function(){i.hide()}));j(g)}),this.$remindBlock.delegate("[data-operation=openLink]","click",function(){var j=$(this).parents("li");i.remindNum--;i.msgNum--;i.$msgNum.text(i.msgNum);i.remindNum?i.$remindDiv.addClass(s):i.$remindDiv.removeClass(s);j.fadeOut("slow",function(){j.remove()})}),this.$noticeBlock.delegate("[data-operation=dismissOne]","click",function(){var i=$(this).parents("li").css("opacity",0.5).data("id");j(i)}),this.$noticeBlock.delegate("[data-operation=dismissAll]",
"click",function(){r.deleteAllNotify(function(){i.dismissIds=[];i.$noticeTitle.html("通知");i.noticeNum=0;i.$noticeBlock.fadeOut("slow",function(){i.$noticeDiv.removeClass(s);i.hide()})})}),$("body").bind("click",function(j){!$.contains(i.$noticeDiv[0],j.target)&&"dismissOne"!==$(j.target).data("operation")&&i.hide();$.contains(i.$remindDiv[0],j.target)||i.hideCertain("remind");$.contains(i.$settingsDiv[0],j.target)||i.hideCertain("settings")}),this.$noticeTitle.click(function(){i._isClosed?i.show():
i.hide()}),this.$remindTitle.click(function(){i.$remindBlock.toggle().parent().toggleClass(p)}),this.$settingsTitle.click(function(){i.$settingsBlock.toggle().parent().toggleClass(p)}),r.onUpdate(function(j,g,o){i.update(j,g,o);i._notify()}),r.onUpdateRemind(function(j){i.updateRemind(j)}))}var p="gactived",s="unread";o.prototype={_isClosed:!0,_init:function(){if(j.get("isN"))this._notify();else{var o=new Date;4<o.getHours()&&o.setDate(o.getDate()+1);o.setHours(4,0,0,0);j.set("isN",1,o);this.noticeNum?
this.show():this._notify()}},_notify:function(){this.remindNum?this.$remindDiv.addClass(s):this.$remindDiv.removeClass(s);this.$noticeNum.text(this.noticeNum);this.noticeNum?this.$noticeDiv.addClass(s):this.$noticeDiv.removeClass(s);this.$noticeBlock.find("ul").html(this.noticeNum?this.noticeList.join(""):"");return this},update:function(j,i,n){this.remindNum=null==j?this.remindNum:j;this.noticeList=n||[];if(5<this.noticeList.length)this.noticeList=this.noticeList.slice(0,5);this.noticeList=$.map(this.noticeList,
function(g){return q('<li data-id="<%=id%>">                                <p><a href="<%=url%>" data-operation="openLink" target="_blank"><%=content%></a></p>                                <a href="javascript: void 0;" class="gicon-close" data-operation="dismissOne">x</a>                            </li>',g)});this.noticeNum=i||0;if(0===this.noticeNum)this.noticeList=[],this.hide();this._notify();return this},updateRemind:function(j){this.msgList=j.message||[];this.draftList=j.draft||[];this.$msgNum.text(this.msgList.length);
this.msgNum=this.msgList.length;this.$draftNum.text(this.draftList.length);this.draftNum=this.draftList.length;if(2<this.msgNum)this.msgList=this.msgList.slice(0,2);if(2<this.draftNum)this.draftList=this.draftList.slice(0,2);this.msgList=$.map(this.msgList,function(i){return q('<li data-id="<%=id%>">                                <p><a href="<%=url%>" data-operation="openLink" target="_blank"><%=content%></a></p>                            </li>',i)});this.$remindBlock.find("ul").eq(0).html(this.msgList.join(""));
this.draftList=$.map(this.draftList,function(i){return q('<li data-id="id">                                <p><a href="<%=url%>" target="_blank"><%=content%></a></p>                            </li>',i)});this.$remindBlock.find("ul").eq(1).html(this.draftList.join(""));return this},hide:function(){this.$noticeBlock.hide();this.$noticeDiv.removeClass(p);this._isClosed=!0;return this},hideCertain:function(j){this["$"+j+"Block"].hide();this["$"+j+"Div"].removeClass(p);return this},show:function(){this._notify();
this.$noticeDiv.addClass(p);this.$noticeBlock.show();this._isClosed=!1;return this}};return function(){return new o}});
G.req(["gPopMenu","cookies","placeholder","missionLoader"],function(j,r){r.remove("gkanalyze");$(function(){G.req(["gPopMenu","cookies","placeholder","missionLoader"],function(j,o,p,r){j("#mMenu");j("#sMenu",!0);$(document).ajaxError(function(j,i,n){"/uploadfile/user_upload"!==n.url&&(406===i.status?(j=$.parseJSON(i.responseText),alert(j.errmsg)):G.log(i.status+": 服务器悲剧了，不是前端bug！不要来烦我 ^_^"))});$("#search").doOnce(function(){var j=$("#searchTxt");p.init(j).submit(j,this,function(){if(!j.val())return!1})});
r();$("body").delegate("a[data-analyze]","click",function(){o.set("gkanalyze",$(this).data("analyze"))})});ukey&&$(document).ready(function(){G.req("notify",function(j){j()})})})});
